<?php
    $avatar = empty($this->arrData['user_avatar']) ? STATIC_URL . '/f/v1/images/noavatar.jpg' : $this->arrData['user_avatar'];
?>
<article class="row">
    <div class="col-md-2 col-sm-2 hidden-xs">
        <figure class="thumbnail">
            <img class="img-responsive" src="<?php echo $avatar; ?>">
            <figcaption class="text-center"></figcaption>
        </figure>
    </div>
    <div class="col-md-10 col-sm-10">
        <div class="panel panel-default arrow left item">
            <div class="panel-body">
                <div class="row">
                    <header class="text-left">
                        <div class="col-md-8"><i class="fa fa-user"></i> <span style="color: #007DFF"><?php echo $this->arrData['full_name'] ?></span></div>
                        <div class="col-md-4 text-right"><i class="fa fa-clock-o"></i> <span style="color: #007DFF"><?php echo My\General::formatDateString($this->arrData['created_date']); ?></span></div>
                    </header>
                </div>
                <div class="row">
                    <div class="col-md-11">
                        <i class="fa fa-envelope"></i> <span style="color: #007DFF"><?php echo $this->arrData['email'] ?></span>
                        <div>
                        </div>
                        <div class="comment-post bor-2-r col-md-12">
                            <p>
                                <?php echo $this->arrData['comm_content']; ?>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</article>