<!--main sub page heading-->
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1><?php echo $this->arrContent['cont_title']; ?></h1>
            </div>
        </div>
    </div>
</section><!--end main page heading-->

<!--Detail -->
<section id="detail">
    <input name="cont_id" value="<?php echo $this->arrContent['cont_id']; ?>" type="hidden">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="ads-detail">
                    <?php
                    $href_user = 'javascript:;';
                    if (!empty($this->arrContent['user_created'])) {
                        $href_user = $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUser['user_fullname']), 'userId' => $this->arrUser['user_id']]);
                    }
                    if (!empty($this->arrContent['cont_image']) && $this->arrContent['cont_image'] != 'null'):
                        $arrImage = json_decode($this->arrContent['cont_image']);
                        ?>
                        <div class="row">
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="ad-slider">
                                    <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
                                        <!-- Carousel indicators -->
                                        <ol class="carousel-indicators">
                                            <?php for ($i = 0; $i < count($arrImage); $i++): ?>
                                                <li data-target="#myCarousel" data-slide-to="<?php echo $i; ?>" class="<?php if ($i == 0): ?>active<?php endif; ?>"></li>
                                            <?php endfor; ?>
                                        </ol>
                                        <!-- Carousel items -->
                                        <div class="carousel-inner">
                                            <?php foreach ($arrImage as $key => $image) : ?>
                                                <div class="<?php if ($key == 0): ?>active<?php endif; ?> item">
                                                    <img src="<?php echo json_decode($image, true)['sourceImage']; ?>" alt="carousel">
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                        <!-- Carousel nav -->
                                        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                                            <i class="fa fa-angle-left"></i>
                                        </a>
                                        <a class="carousel-control right" href="#myCarousel" data-slide="next">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div><!--end carousel-->
                                </div><!--end ad-slider-->
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="author-detail">
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="author-avatar">
                                    <?php
                                    $avatar = STATIC_URL . '/f/v1/images/noavatar.jpg';
                                    if (!empty($this->arrUser['user_avatar'])) {
                                        $avatar = json_decode($this->arrUser['user_avatar'], true)[0]['thumbImage']['120x120'];
                                    }
                                    ?>
                                    <img src="<?php echo $avatar; ?>" alt="author avatar">
                                </div>
                                <div class="author-name">
                                    <a style="text-decoration: none;" href="<?php echo $href_user; ?>"><p><?php echo $this->arrUser['user_fullname'] ?></p></a>
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <div class="author-detail-right">
                                    <div class="row">
                                        <div class="author-info">
                                            <i class="fa fa-phone"></i>
                                            <p>Số điện thoại : <?php echo $this->arrUser['user_phone']; ?></p>
                                        </div>
                                        <div class="author-info">
                                            <i class="fa fa-globe"></i>
                                            <p>Email: <a class="col" href="#"> <?php echo $this->arrUser['user_email']; ?> </a></p>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12 text-center">
                                            <?php if (!(!empty($this->arrContent['user_created']) && ($this->arrContent['user_created'] == CUSTOMER_ID))): ?>
                                                <a class="btn btn-success <?php echo CUSTOMER_ID ? 'save-post' : 'no-login'; ?>" data-toggle="tooltip" title="Lưu lại tin này">
                                                    <i class="fa fa-save"></i>
                                                </a>
                                            <?php endif; ?>
                                            <span data-toggle="modal" data-target="#ModalUpVip">
                                                <a class="btn btn-warning" data-toggle="tooltip" title="Úp víp" data-toggle="modal" data-target="#myModal">
                                                    <i class="fa fa-star-o"></i>
                                                </a>
                                            </span>
                                            <?php if (!(!empty($this->arrContent['user_created']) && ($this->arrContent['user_created'] == CUSTOMER_ID))): ?>
                                                <a class="btn btn-success <?php echo CUSTOMER_ID ? 'modal-messages' : 'no-login'; ?>" data-toggle="tooltip" title="Gửi tin nhắn cho người đăng!">
                                                    <i class="fa fa-envelope-o"></i>
                                                </a>
                                            <?php endif; ?>
                                            <?php if (empty($this->arrContent['user_created'])) : ?>
                                                <a class="btn btn-primary modal-confirm-pass" data-toggle="tooltip" title="Sửa tin">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a class="btn btn-danger delete-content" data-toggle="tooltip" title="Xóa tin">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                            <?php endif; ?>
                                        </div>

                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
                $category_parent = unserialize(ARR_CATEGORY)[unserialize(ARR_CATEGORY)[$this->arrContent['cate_id']]['parent_id']];
                $arrCategory = unserialize(ARR_CATEGORY)[$this->arrContent['cate_id']];
                ?>
                <div class="ad-detail">

                    <div class="ad-detail-head">
                        <i class="fa <?php echo str_replace('icon', 'fa', $category_parent['cate_icon']); ?> fa-2x"></i>
                        <h4 class="ad-cat"><a style="text-decoration: none" href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $arrCategory['cate_slug'], 'cateId' => $arrCategory['cate_id'])) ?>"><?php echo $arrCategory['cate_name'] ?></a></h4>
                    </div>

                    <div class="ad-detail-info clearfix">
                        <p class="pull-left"> <i class="fa fa-barcode" aria-hidden="true"></i>  Mã tin :</p>
                        <p class="pull-right light"><a href="javascript:;" style="text-decoration: none"><b>RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b></a></p>
                    </div>

                    <div class="ad-detail-info clearfix">
                        <p class="pull-left"> <i class="fa fa-globe" aria-hidden="true"></i>  Khu vực :</p>
                        <p class="pull-right light"><a href="javascript:;" style="text-decoration: none; font-weight: bold;"><?php echo (!empty($this->arrContent['dist_id'])) ? unserialize(ARR_DISTRICT)[$this->arrContent['dist_id']]['dist_name'] : 'Toàn tỉnh'; ?></a></p>
                    </div>

                    <?php if (!empty($this->arrProperties)): ?>
                        <div class="ad-detail-info clearfix">
                            <p class="pull-left"> <i class="fa fa-shopping-cart" aria-hidden="true"></i>  Nhu cầu :</p>
                            <p class="pull-right light"><a href="javascript:;" style="text-decoration: none; font-weight: bold;"><?php echo $this->arrProperties['prop_name']; ?></a></p>
                        </div>
                    <?php endif; ?>

                    <div class="ad-detail-info clearfix">
                        <p class="pull-left"><i class="fa fa-clock-o"></i> Đăng lúc :</p>
                        <p class="pull-right light"><a href="javascript:;" style="text-decoration: none"><b><?php echo date('d/m/Y H:i', $this->arrContent['created_date']); ?></b></a></p>
                    </div>
                    <div class="ad-detail-info clearfix">
                        <p class="pull-left"><i class="fa fa-eye" aria-hidden="true"></i> Số lượt xem :</p>
                        <p class="pull-right light"><a href="javascript:;" style="text-decoration: none"><b><?php echo $this->arrContent['cont_views']; ?></b></a></p>
                    </div>

                    <div class="ad-detail-info clearfix">
                        <p>Nội dung :</p>
                        <?php // echo $this->arrContent['from_soucre'] == 'raovatquynhon.com' ? $this->arrContent['cont_detail_text'] : $this->arrContent['cont_detail']; ?>
                        <?php echo html_entity_decode($this->arrContent['cont_detail']); ?>
                    </div>
                </div>
                <div class="tags">
                    <div class="col-md-6 col-xs-6">
                        <div class="fb-like" data-href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id']]) ?>" data-layout="button_count" data-action="like" data-show-faces="true" data-share="true"></div>

                    </div>
                    <div class="col-md-6 col-xs-6">
                        <g:plusone></g:plusone>
                    </div>
                </div>
                <div class="tags">
                    <i class="fa fa-tags"></i>
                    <span>Tags:</span>
                    <span> Expensive Cars, Red, Black, WordPress, Classified, Ads</span>
                </div>
                <!--</div>end ad-detail-->
                <!--advertisement-->
                <div class="advert">
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/detail-page-ad_03.png" alt="ad"> </a>
                </div>

                <!--form submission-->
                <div id="form" class="row border-buttom">
                    <h4 class="inner-heading">PHẢN HỒI</h4>
                    <form id="post-commet">
                        <div class="col-sm-6 input-pad">
                            <span class="fa fa-user form-control-feedback"></span>
                            <input class="form-control" type="text" name="full_name" placeholder="Ex : Nguyễn Văn A" value="<?php echo!empty(CUSTOMER_ID) ? CUSTOMER_FULLNAME : ''; ?>" <?php if (!empty(CUSTOMER_ID)): ?>readonly<?php endif; ?>>
                            <span class="comment-error-name" style="color: red; display: none"></span>
                        </div>
                        <div class="col-sm-6 input-pad">
                            <span class="fa fa-envelope form-control-feedback"></span>
                            <input class="form-control" type="text" name="email" placeholder="Ex : abcxyz@gmail.com" value="<?php echo!empty(CUSTOMER_ID) ? CUSTOMER_EMAIL : ''; ?>" <?php if (!empty(CUSTOMER_ID)): ?>readonly<?php endif; ?>>
                            <span class="comment-error-email" style="color: red; display: none"></span>
                        </div>
                        <div class="col-sm-12 padding-control">
                            <textarea class="form-control" name="comment-content"></textarea>
                            <span class="comment-error-content" style="color: red; display: none"></span>
                        </div>
                        <!--<input type="text" name="humantest">-->
                    </form>
                    <div class="row">
                        <div class="col-md-2 col-xs-2 control-label">
                            <img class="img-captcha form-control" src=""/>
                        </div>
                        <div class="col-md-6 col-xs-6">
                            <input name="captcha" type="text" class="form-control" placeholder="Nhập mã bên cạnh">
                            <span class="comment-error-captcha" style="color: red; display: none"></span>
                        </div>
                        <div class="col-md-2 col-xs-2">
                            <a class="btn refresh-captcha" data-toggle="tooltip" title="Lấy mã mới"><i class="fa fa-2x fa-refresh"></i></a>
                        </div>
                        <div class="col-md-2 col-xs-2"><button class="btn btn-primary pull-right add-comment">Gửi phản hồi</button></div>
                    </div>
                </div>
                <!--end form submission-->
                <div class="row" style="margin-top: 10px">
                    <h4 class="inner-heading">DANH SÁCH PHẢN HỒI</h4>
                    <section class="comment-list comment-list-post">
                        <?php
                        if (!empty($this->arrCommentList)):
                            foreach ($this->arrCommentList as $comment):
                                $avatar = empty($comment['user_avatar']) ? STATIC_URL . '/f/v1/images/noavatar.jpg' : $comment['user_avatar'];
                                ?>
                                <article class="row">
                                    <div class="col-md-2 col-sm-2 hidden-xs">
                                        <figure class="thumbnail">
                                            <img class="img-responsive" src="<?php echo $avatar; ?>">
                                            <figcaption class="text-center"></figcaption>
                                        </figure>
                                    </div>
                                    <div class="col-md-10 col-sm-10">
                                        <div class="panel panel-default arrow left item">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <header class="text-left">
                                                        <div class="col-md-8"><i class="fa fa-user"></i> <span style="color: #007DFF"><?php echo $comment['full_name'] ?></span></div>
                                                        <div class="col-md-4 text-right"><i class="fa fa-clock-o"></i> <span style="color: #007DFF"><?php echo My\General::formatDateString($comment['created_date']); ?></span></div>
                                                    </header>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-11">
                                                        <i class="fa fa-envelope"></i> <span style="color: #007DFF"><?php echo $comment['email'] ?></span>
                                                        <div>
                                                        </div>
                                                        <div class="comment-post bor-2-r col-md-12">
                                                            <?php echo $comment['comm_content']; ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                                <?php
                            endforeach;
                        endif;
                        ?>
                    </section>
                </div>
                <div class="fb-comments" data-href="<?php echo $this->serverUrl() . $this->Url('view-content', array('contentSlug' => $this->arrContent["cont_slug"], 'cont_id' => $this->arrContent["cont_id"])) ?>" data-width="100%" data-numposts="5"></div>


                <?php if (!empty($this->arrContentLastedList)): ?>
                    <div id="relatedAds">
                        <div class="row">
                            <section class="panel">
                                <div class="panel-body" style="padding: 0px">    
                                    <div class="adv-table editable-table">
                                        <section id="unseen">
                                            <table class="table table-hover table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th><h4>Có thể bạn quan tâm</h4></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    foreach ($this->arrContentLastedList as $content):
                                                        $description = (strlen(html_entity_decode($content['cont_detail_text'])) > 400) ? substr(html_entity_decode($content['cont_detail_text']), 0, 400) . '...' : html_entity_decode($content['cont_detail_text']);
                                                        ?>
                                                        <tr>
                                                            <td style="vertical-align: middle">
                                                                <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $content['cont_slug'], 'contentId' => $content['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip <?php if ($content['vip_type'] == \My\General::VIP_CATE_PAGE): ?>vip2<?php elseif ($content['vip_type'] == \My\General::VIP_ALL_PAGE):; ?> color-red<?php endif; ?>" style="text-decoration: none;">
                                                                    <?php echo $content['cont_title']; ?>
                                                                </a>
                                                                <span class="success">( <i class="fa fa-calendar-o" aria-hidden="true"></i><?php echo date('d/m', $content['created_date']); ?> | <i class="fa fa-eye"> <?php echo (int) $content['cont_views']; ?></i> | <i class="fa fa-comment-o" aria-hidden="true"> <?php echo (int) $content['total_comment']; ?></i> )</span>
                                                                <?php if ($content['vip_type'] == \My\General::VIP_CATE_PAGE): ?><img src="<?php echo \My\General::IMAGE_VIP ?>"><?php elseif ($content['vip_type'] == \My\General::VIP_ALL_PAGE): ?><img src="<?php echo \My\General::IMAGE_SVIP ?>"><?php endif; ?>
                                                            </td>
                                                        </tr>
                                                    <?php endforeach; ?>
                                                </tbody>
                                            </table>
                                        </section>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
            <div class="col-md-4">
                <?php echo $this->render('frontend/nav-ads-right'); ?>
            </div>
        </div>
    </div>
</section><!--end details-->
<div class="modal fade" id="ModalSendMessages" tabindex="-1" role="dialog" aria-labelledby="ModalSendMessages">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">Gửi tin nhắn cho người đăng tin</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="message-text" class="control-label">Nội dung:</label> <b class="error-messages" style="color: red; display: none"></b>
                        <textarea class="form-control" id="message-text" rows="5"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                <button type="button" class="btn btn-success send-messages">Gửi tin nhắn</button>
            </div>
        </div>
    </div>
</div>
<?php
if (empty($this->arrContent['user_created'])):
    ?>
    <div class="modal fade" id="confirm-pass-cont" tabindex="-1" role="dialog" aria-labelledby="ModalConfirmPass">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Mật khẩu để sửa tin</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <b class="error-pass-content" style="color: red; display: none"></b>
                            <input class="form-control" id="pass-content" type="password"> 
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-success send-pass-content">Xác nhận</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="ModalConfirmPass">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="exampleModalLabel">Mật khẩu để sửa tin</h4>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <b class="error-delete" style="color: red; display: none"></b>
                            <input class="form-control" id="pass-delete" type="password"> 
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Hủy</button>
                    <button type="button" class="btn btn-success confirm-delete">Xác nhận</button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<?php if (empty(CUSTOMER_ID)): ?>
    <div class="modal fade" id="ModalUpVip" tabindex="-1" role="dialog" aria-labelledby="ModalUpVip">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Mua víp cho tin</h4>
                </div>
                <div class="modal-body">
                    <div class="border-detail form-control timeline-desk">
                        <p style="color: blue">Bạn có thể nhắn tin theo cú pháp : </p> 
                        <p><b style="color: red">BQN SVIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7650</b> để mua <b style="color: red">2 </b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>"> cho tin</p>
                        <p><b style="color: red">BQN SVIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7750</b> để mua <b style="color: red">3</b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>"> cho tin</p>
                        <p style="color: blue">Hoặc nhắn tin theo cú pháp : </p> 
                        <p><b style="color: red">BQN VIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7650</b> để mua <b style="color: red">5 </b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>"> cho tin</p>
                        <p><b style="color: red">BQN VIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7750</b> để mua <b style="color: red">8</b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>"> cho tin</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="modal fade" id="ModalUpVip" tabindex="-1" role="dialog" aria-labelledby="ModalUpVip">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">MUA VÍP CHO RAO VẶT</h4>
                </div>
                <div class="modal-body">
                    <h5>BẰNG TIN NHẮN</h5>
                    <div class="row border-detail form-control timeline-desk">
                        <p style="color: blue">Bạn có thể nhắn tin theo cú pháp : </p> 
                        <p><b style="color: red">BQN SVIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7650</b> để mua <b style="color: red">2 </b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>"> cho tin</p>
                        <p><b style="color: red">BQN SVIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7750</b> để mua <b style="color: red">3</b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>"> cho tin</p>
                        <p style="color: blue">Hoặc nhắn tin theo cú pháp : </p> 
                        <p><b style="color: red">BQN VIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7650</b> để mua <b style="color: red">5 </b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>"> cho tin</p>
                        <p><b style="color: red">BQN VIP RV<?php echo sprintf("%04d", $this->arrContent['cont_id']); ?></b> gửi <b style="color: red">7750</b> để mua <b style="color: red">8</b> ngày <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>"> cho tin</p>
                    </div>
                    <h5>HOẶC BẰNG SỐ DƯ TÀI KHOẢN</h5>
                    <div class="row border-detail form-control timeline-desk">
                        <input type="hidden" name="blance" value="<?php echo CUSTOMER_BALANCE; ?>">
                        <div class="col" style="margin: 5px 0px 10px 0">
                            <p><b class="color-blue">Số dư tài khoản của bạn là : </b><b class="color-red"><?php echo number_format(CUSTOMER_BALANCE, 0, ",", "."); ?>đ</b></p>
                        </div>
                        <div class="col" style="margin: 5px 0px 10px 0">
                            <p><img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>">  <b class="color-blue">= 5000đ/Ngày</b> <b style="color: red"> Hoặc </b> <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>"> <b class="color-blue">= 2000đ/Ngày</b></p>
                        </div>
                        <div class="col">
                            <div class="col-md-4">
                                <p  style="margin-bottom: 5px; color: blue">Chọn Loại Víp</p>
                                <input class="radio" type="radio" value="<?php echo My\General::VIP_ALL_PAGE; ?>" name="typevip" checked><img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>">
                                <input class="radio" type="radio" value="<?php echo My\General::VIP_CATE_PAGE; ?>" name="typevip"><img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif'; ?>">
                            </div>
                            <div class="col-md-3">
                                <p  style="margin-bottom: 5px; color: blue">Số ngày</p>
                                <input type="number" class="form-control input-sm" name="numdate" min="1">
                            </div>
                            <div class="col-md-3 mg-t-18 total-fee" style="display: none">
                            </div>
                            <div class="col-md-2 mg-t-18">
                                <button class="btn btn-success" name="deal-vip">Mua</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
<script src="https://apis.google.com/js/platform.js" async defer>
    {
        lang: 'vi'
    }
</script>
<script>
    var cont_id = '<?php echo $this->arrContent['cont_id']; ?>';
    saveContentURL = '<?php echo $this->serverUrl() . $this->Url('content', array('action' => 'save-content')); ?>';
    sendMessagesURL = '<?php echo $this->serverUrl() . $this->Url('content', array('action' => 'send-messages')); ?>';
    addCommentURL = '<?php echo $this->serverUrl() . $this->Url('add-comment'); ?>';
    confirmPassContURL = '<?php echo $this->serverUrl() . $this->Url('confirm-pass-content'); ?>';
    deleteContentURL = '<?php echo $this->serverUrl() . $this->Url('content', ['action' => 'delete-content']); ?>';
    dealVipURL = '<?php echo $this->serverUrl() . $this->Url('deal-vip-content'); ?>';
    Content.detail();
</script>