<?php ?>
<!--main sub page heading-->
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1><?php echo $this->arrContent['cont_title']; ?></h1>
            </div>
        </div>
    </div>
</section><!--end main page heading-->

<!--Detail -->
<section id="detail">
    <input name="cont_id" value="<?php echo $this->arrContent['cont_id']; ?>" type="hidden">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="ads-detail">
                    <?php
                    if (empty($this->arrContent['cont_image'])):
                        $arrImage = json_decode($this->arrContent['cont_image']);
                        ?>
                        <div class="row">
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="ad-slider">
                                    <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
                                        <!-- Carousel indicators -->
                                        <ol class="carousel-indicators">
                                            <?php for ($i = 0; $i < count($arrImage); $i++): ?>
                                                <li data-target="#myCarousel" data-slide-to="<?php echo $i; ?>" class="<?php if ($i == 0): ?>active<?php endif; ?>"></li>
                                            <?php endfor; ?>
                                        </ol>
                                        <!-- Carousel items -->
                                        <div class="carousel-inner">
                                            <?php foreach ($arrImage as $key => $image) : ?>
                                                <div class="<?php if ($key == 0): ?>active<?php endif; ?> item">
                                                    <img src="<?php echo json_decode($image, true)['sourceImage']; ?>" alt="carousel">
                                                </div>
                                            <?php endforeach; ?>
                                        </div>
                                        <!-- Carousel nav -->
                                        <a class="carousel-control left" href="#myCarousel" data-slide="prev">
                                            <i class="fa fa-angle-left"></i>
                                        </a>
                                        <a class="carousel-control right" href="#myCarousel" data-slide="next">
                                            <i class="fa fa-angle-right"></i>
                                        </a>
                                    </div><!--end carousel-->
                                </div><!--end ad-slider-->
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="author-detail">
                        <div class="row">
                            <div class="col-sm-3">
                                <div class="author-avatar">
                                    <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/author-avatar_03.png" alt="author avatar">
                                </div>
                                <div class="author-name">
                                    <p>John Terry</p>
                                </div>
                            </div>
                            <div class="col-sm-9">
                                <div class="author-detail-right">
                                    <div class="author-info">
                                        <i class="fa fa-map-marker"></i>
                                        <p>Địa chỉ: BX 201 livingston street, Brooklyn New York</p>
                                    </div>
                                    <div class="author-info">
                                        <i class="fa fa-phone"></i>
                                        <p>Số điện thoại: +(646) 45321069</p>
                                    </div>
                                    <div class="author-info">
                                        <i class="fa fa-globe"></i>
                                        <p>Email: <a class="col" href="#"> ngocchien01@gmail.com </a></p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php
                $category_parent = unserialize(ARR_CATEGORY)[unserialize(ARR_CATEGORY)[$this->arrContent['cate_id']]['parent_id']];
                ?>
                <div class="ad-detail">
                    <div class="ad-detail-head">
                        <i class="fa <?php echo str_replace('icon', 'fa', $category_parent['cate_icon']); ?> fa-2x"></i>
                        <h4 class="ad-cat"> Danh mục : <?php echo $category_parent['cate_name'] ?></h4>
                    </div>
                    <div class="ad-detail-info clearfix">
                        <p class="pull-left">Ngày đăng :</p>
                        <p class="pull-right light"><?php echo date('d/m/Y', $this->arrContent['created_date']); ?></p>
                    </div>
                    <div class="ad-detail-info clearfix">
                        <p class="pull-left">Số lượt xem :</p>
                        <p class="pull-right light"><?php echo $this->arrContent['cont_views']; ?></p>
                    </div>

                    <div class="ad-detail-info clearfix">
                        <p>Nội dung :</p>
                        <?php echo $this->arrContent['cont_detail']; ?>
                    </div>

                    <div class="tags">
                        <i class="fa fa-tags"></i>
                        <span>Tags:</span>
                        <span> Expensive Cars, Red, Black, WordPress, Classified, Ads</span>
                    </div>
                </div><!--end ad-detail-->
                <!--advertisement-->
                <div class="advert">
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/detail-page-ad_03.png" alt="ad"> </a>
                </div>

                <!--form submission-->
                <div id="form">
                    <h4 class="inner-heading">PHẢN HỒI</h4>
                    <div class="row">

                    </div>
                    <form id="post-commet">
                        <div class="col-sm-6 input-pad">
                            <span class="comment-error-name" style="color: red; display: none"></span>
                            <span class="fa fa-user form-control-feedback"></span>
                            <input class="form-control" type="text" name="full_name" placeholder="Ex : Nguyễn Văn A" value=" <?php echo!empty(CUSTOMER_ID) ? CUSTOMER_FULLNAME : ''; ?>" <?php if (!empty(CUSTOMER_ID)): ?>readonly<?php endif; ?>>
                        </div>
                        <div class="col-sm-6 input-pad">
                            <span class="comment-error-email" style="color: red; display: none"></span>
                            <span class="fa fa-envelope form-control-feedback"></span>
                            <input class="form-control" type="email" name="email" placeholder="Ex : abcxyz@gmail.com" value=" <?php echo!empty(CUSTOMER_ID) ? CUSTOMER_EMAIL : ''; ?>" <?php if (!empty(CUSTOMER_ID)): ?>readonly<?php endif; ?>>
                        </div>
                        <div class="col-sm-12 padding-control">
                            <span class="comment-error-content" style="color: red; display: none"></span>
                            <textarea class="form-control" name="comment-content"></textarea>
                        </div>
                        <!--<input type="text" name="humantest">-->
                    </form>
                    <div class="col-sm-12 padding-control">
                        <button class="btn btn-primary pull-right add-comment">Gửi phản hồi</button>
                    </div>
                </div>
                <!--end form submission-->
                <div class="col-md-12 col-xs-12 col-sm-12 padding-control">
                    <section class="comment-list comment-list-post">
                        <?php
                        if (!empty($this->arrCommentList)):
                            foreach ($this->arrCommentList as $comment):
                                ?>
                                <article class="row item-<?php echo $comment['comm_id']; ?>">
                                    <div class="col-md-2 col-sm-2 hidden-xs">
                                        <figure class="thumbnail">
                                            <img class="img-responsive" src="<?php echo json_decode($this->arrListUserComment[$value['user_id']]['user_avatar'], true)[0]['thumbImage']['120x120']; ?>">
                                            <figcaption class="text-center"></figcaption>
                                        </figure>
                                    </div>
                                    <div class="col-md-10 col-sm-10">
                                        <div class="panel panel-default arrow left item">
                                            <div class="panel-body">
                                                <div class="row">
                                                    <header class="text-left">
                                                        <div class="col-md-4"><i class="fa fa-user"></i> <?php echo $comment['full_name'] ?></div>
                                                        <div class="col-md-8"><i class="fa fa-envelope"></i> <?php echo $comment['email'] ?></div>
                                                    </header>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-11">
                                                        <i class="fa fa-clock-o"></i> <?php echo My\General::formatDateString($comment['created_date']); ?>
                                                    <div>
                                                </div>
                                                <div class="comment-post">
                                                    <p>
                                                        <?php echo $comment['comm_content']; ?>
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </article>
                                <?php
                            endforeach;
                        endif;
                        ?>
                    </section>
                </div>
                <div class="fb-comments" data-href="<?php // echo $this->serverUrl() . $this->Url('product', array('productslug' => $this->arrProductDetail["prod_slug"], 'productId' => $this->arrProductDetail["prod_id"]))         ?>" data-width="100%" data-numposts="5"></div>

                <!--Related Ads-->
                <div id="relatedAds">
                    <h4 class="inner-heading">RELATED ADs</h4>
                    <div class="row">
                        <div class="col-sm-4 padding-control">
                            <div class="ads">
                                <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/relatedad1_03.png"></a>
                                <div class="ads-title"><p><a href="#">Classic Red Bike</a></p></div>
                                <a href="#" class="ads-hover">
                                    <span>$1,000</span>
                                    <i class="fa fa-cab fa-2x"></i>
                                </a>
                            </div>
                        </div>

                        <div class="col-sm-4 padding-control">
                            <div class="ads">
                                <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/relatedad2_03.png"></a>
                                <div class="ads-title"><p><a href="#">Expensive Car</a></p></div>
                                <a href="#" class="ads-hover">
                                    <span>$3,000</span>
                                    <i class="fa fa-cab fa-2x"></i>
                                </a>
                            </div>
                        </div>

                        <div class="col-sm-4 padding-control">
                            <div class="ads">
                                <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/relatedad3_03.png"></a>
                                <div class="ads-title"><p><a href="#">Antique things for sale</a></p></div>
                                <a href="#" class="ads-hover">
                                    <span>$5,000</span>
                                    <i class="fa fa-cab fa-2x"></i>
                                </a>
                            </div>
                        </div>
                    </div>
                </div><!--end related ads-->

            </div>
            <div class="col-md-4">
                <div class="sidebar">
                    <div class="side-widget clearfix">
                        <h4 class="inner-heading">PREMIUM ADs</h4>
                        <div class="col-md-12 col-sm-4">
                            <div class="premium-widget">
                                <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/sideimg1_03.png">
                                <a href="#" class="item-hover"><span>$199</span></a>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-4">
                            <div class="premium-widget">
                                <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/sideimg2_03.png">
                                <a href="#" class="item-hover"><span>$199</span></a>
                            </div>
                        </div>
                        <div class="col-md-12 col-sm-4">
                            <div class="premium-widget">
                                <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/sideimg3_03.png">
                                <a href="#" class="item-hover"><span>$199</span></a>
                            </div>
                        </div>
                    </div><!--end premium widget-->

                    <div class="side-widget">
                        <h4 class="inner-heading">Latest ADs</h4>
                        <div class="sidebar-latest-ad">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/side-latest-ad-img1_03.png" alt="side ads">
                                </div>
                                <div class="col-sm-8">
                                    <p><a href="#" class="col"> M26r Car 2014</a></p>
                                    <p>$40,000</p>
                                    <p>Condition 10/10 & fully original all parts...</p>
                                </div>
                            </div>
                        </div>

                        <div class="sidebar-latest-ad">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/side-latest-ad-img2_03.png" alt="side ads">
                                </div>
                                <div class="col-sm-8">
                                    <p><a href="#" class="col"> M26r Car 2014</a></p>
                                    <p>$40,000</p>
                                    <p>Condition 10/10 & fully original all parts...</p>
                                </div>
                            </div>
                        </div>

                        <div class="sidebar-latest-ad">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/side-latest-ad-img3_03.png" alt="side ads">
                                </div>
                                <div class="col-sm-8">
                                    <p><a href="#" class="col"> M26r Car 2014</a></p>
                                    <p>$40,000</p>
                                    <p>Condition 10/10 & fully original all parts...</p>
                                </div>
                            </div>
                        </div>

                        <div class="sidebar-latest-ad">
                            <div class="row">
                                <div class="col-sm-4">
                                    <img src="<?php echo STATIC_URL; ?>/f/v1/images/images/side-latest-ad-img4_03.png" alt="side ads">
                                </div>
                                <div class="col-sm-8">
                                    <p><a href="#" class="col"> M26r Car 2014</a></p>
                                    <p>$40,000</p>
                                    <p>Condition 10/10 & fully original all parts...</p>
                                </div>
                            </div>
                        </div>
                    </div><!--end latest ad widget-->

                    <!--advertisement-->
                    <div class="side-widget">
                        <h4 class="inner-heading">ADVERTISEMENT</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div><!--end advertisement widget-->

                    <!--Tags-->
                    <div class="side-widget">
                        <h4 class="inner-heading">Tags</h4>
                        <div class="tags">
                            <a href="#">Ads</a>
                            <a href="#">Design</a>
                            <a href="#">Classified</a>
                            <a href="#">PSD’s</a>
                            <a href="#">Advertisement</a>
                            <a href="#">Jobs</a>
                            <a href="#">Community</a>
                            <a href="#">Business</a>
                            <a href="#">Interior</a>
                            <a href="#">Condo</a>
                            <a href="#">Pet</a>
                            <a href="#">Shopping</a>
                            <a href="#">Clothing</a>
                            <a href="#">Vehicles</a>


                        </div>
                    </div><!--end tags widget-->
                </div>
            </div>
        </div>
    </div>
</section><!--end details-->
<script>
    addCommentURL = '<?php echo $this->serverUrl() . $this->Url('add-comment'); ?>';
    Content.detail();
</script>