<?php
$arrImage = $this->arrImage;
?>
<div class="img-prod">
    <img class="prod-images" src="<?php echo $arrImage[0]['thumbImage']['150x100']; ?>"><br/>
    <div class="pull-right">
        <a target="_bank" href="<?php echo $arrImage[0]['sourceImage']; ?>" class="tooltips view-images" data-placement="top" data-original-title="Xem"><i class="fa fa-search"></i></a>
        <a class="tooltips delete-images" data-placement="top" data-original-title="Xóa"><i class="fa fa-trash-o"></i></a>
    </div>
    <input type="hidden" class="main-images" name='image_prod[]' value='<?php echo json_encode($arrImage[0]); ?>'/>
</div>