<div id="content">
    <div class="block-head">
        <?php
            echo $this->render('frontend/menu');
        ?>
        <div class="breadcrumb">
            <div class="item item-start">
                <div class="ar-right">
                    <div class="cont">
                        <a href="#">Home</a>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="ar-right">
                    <div class="cont">
                        <a href="#">Te  dsadas á dá dsad st</a>
                    </div>
                </div>
            </div>
            <div class="item item-end">
                <div class="ar-right">
                    <div class="cont">
                        <a href="#">Home</a>
                    </div>
                </div>
            </div>
            <div class="item  active">
                <div class="ar-right">
                    <div class="cont">
                        bài viets o day
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <div class="left">
            <div class="box">
                <div class="head box-head">Chăm sóc da</div>
                <div class="cont">
                    <ul class="menu">
                        <li class="item active opened">
                            <a href=""> Chăm sóc da mặt</a>
                            <ul class="item-sub level1">
                                <li class="item opened">
                                    <a href=""> face-clear</a>
                                    <ul class="item-sub level1">
                                        <li class="item opened">
                                            <a href=""> face-clear</a>
                                        </li>
                                        <li class="item unopened">
                                            <a href=""> test</a>
                                        </li>
                                        <li class="item unopened">
                                            <a href=""> test</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="item unopened">
                                    <a href=""> test</a>
                                </li>
                                <li class="item unopened">
                                    <a href=""> test</a>
                                </li>
                            </ul>
                        </li>
                        <li class="item">
                            <a href=""> face-clear</a>
                        </li>
                        <li class="item">
                            <a href=""> face-clear</a>
                        </li>
                        <li class="item">
                            <a href=""> face-clear</a>
                        </li>
                        <li class="item">
                            <a href=""> face-clear</a>
                        </li>
                        <li class="item">
                            <a href=""> test</a>
                        </li>
                        <li class="item">
                            <a href=""> test</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="line"></div>
            <div class="box">
                <div class="head">Giá sản phẩm</div>
                <div class="cont">
                    <div class="sider-select">
                        <input class="range-slider" type="hidden" value="10000,10000000"/>
                    </div>
                    <div class="texbox">
                        <input class="text price-from" value="0" name=""/> VNĐ ->  <input class="text  price-to" value="10000000" name=""/> VNĐ <button class="search ">Tìm</button>
                    </div>
                </div>
            </div>
            <div class="line"></div>
            <div class="box">
                <div class="head">Thương hiệu</div>
                <div class="cont">
                    <div class="selected">
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox1" checked="checked">
                            <label for="checkbox1" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox2" checked="checked">
                            <label for="checkbox2" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox3" checked="checked">
                            <label for="checkbox3" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox4" checked="checked">
                            <label for="checkbox4" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox5" checked="checked">
                            <label for="checkbox5" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox6" checked="checked">
                            <label for="checkbox6" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox7" checked="checked">
                            <label for="checkbox7" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox1" checked="checked">
                            <label for="checkbox1" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox2" checked="checked">
                            <label for="checkbox2" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox3" checked="checked">
                            <label for="checkbox3" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox4" checked="checked">
                            <label for="checkbox4" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox5" checked="checked">
                            <label for="checkbox5" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox6" checked="checked">
                            <label for="checkbox6" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                        <div class="item">
                            <input type="checkbox" class="css-checkbox" id="checkbox7" checked="checked">
                            <label for="checkbox7" name="checkbox1_lbl" class="css-label lite-green-check">Green Check</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="line"></div>
        </div>

        <div class="main">
            <div class="banner">
                <img class="lazy" data-original="images/banner.png"/>
            </div>
            <div class="list-prod">
                <div class="title">
                    <h1>Chăm sóc da</h1>
                </div>
                <div class="bar">
                    <div class="tabs">
                        <div class="item active" data-view="grid">
                            <div class="icon grid">

                            </div>
                        </div>
                        <div class="item" data-view="list">
                            <div class="icon list">

                            </div>
                        </div>
                    </div>

                    <div class="chonse">
                        <div class="sort">
                            Sắp theo 
                            <select>
                                <option>Theo giá</option>
                                <option>Thứ tự</option>
                                <option>1bc</option>
                            </select>
                        </div>
                        <div class="pagging">
                            Xem
                            <select>
                                <option>1</option>
                                <option>2</option>
                                <option>3</option>
                            </select> /  Trang
                        </div>
                    </div>
                </div>
                <div class="sort-by">
                    <div class="item">Thương hiệu abcd <span class="remove">X</span></div>
                    <div class="item">Thương hiệu abcd <span class="remove">X</span></div>
                    <div class="item">Thương hiệu abcd <span class="remove">X</span></div>
                    <div class="remove-all">
                        <a href="#" >Xóa tất cả</a>
                    </div>
                </div>
            </div>
            <div class="view-list list">

                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>

                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>

                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>

                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>

                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div class="item">
                    <div class="img">
                        <a href="#" title="" > <img class="lazy" data-original="images/100x100thumb_muathuoctot.com_142102865537166840.jpg"/></a>
                    </div>
                    <div class="icon">
                        <div class="gift"></div>
                        <div class="discount">60%</div>
                    </div>
                    <div class="info">
                        <div class="title">
                            <a href="#" title="" > Tẩy tế bào chết tái tạo</a>
                        </div>
                        <div class="rate">
                            <div class="star star-15">(10 đánh giá)</div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                        </div>
                        <div class="price">
                            <div class="current">
                                90.000 VNĐ
                            </div>
                            <div class="promot">
                                80.000 VNĐ
                            </div>
                        </div>
                        <div class="desc">
                            Thực Phẩm Chức Năng Now chitosan được bào chế từ chất xơ có nguồn gốc từ vỏ của động vật giáp xác có liên kết với chất béo và cholesterol trong đường tiêu hóa ,Sản phấm Chitosan chứa Chitosan Ultra một dạng mật độ cao cấp bằng sáng chế của Chitosan có liên kết đến chất béo đến 5 lần so với thông thường .Một nghiên cứu lâm sàng được công bố chứng minh rằng Chitosan Ultra có thẻ hổ trợ thêm các cấp trọng lượng cơ thể kết hợp với Chromium( Crôm) là chất giữ vai trò quan trọng trong quá trình chuyển hóa glucose ngăn ngừa chất béo,giảm cảm giác thèm ăn,kiểm soát cân nặng hiệu quả.Sản phẩm đạt tiêu chuẩn thực hành sản xuất thuốc tốt (GMP) của Mỹ
                        </div>
                        <div class="read-more"><a href="#">Xem chi tiết</a></div>
                    </div>
                </div>
                <div style="clear: both"></div>
            </div>
            <div class="paging">
                <ul class="page">
                    <li><a href=""><</a></li>
                    <li class="active"><a href="">1</a></li>
                    <li><a href="">2</a></li>
                    <li><a href="">3</a></li>
                    <li><a href="">...</a></li>
                    <li><a href="">90</a></li>
                    <li><a href="">91</a></li>
                    <li><a href="">></a></li>
                </ul>
            </div>
        </div>

        <div style="clear: both;"></div>
    </div><!-- End block-content -->
</div>