<!--Detail -->
<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <!--Related Ads-->
                <div id="relatedAds">
                    <div class="row">
                        <div class="sidebar">
                            <section class="panel panel-primary">
                                <div class="panel-body" style="padding: 0px">
                                    <div class="row border-buttom">
                                        <div class="col-md-12" style="margin-top: 10px">
                                            <div class="col-md-9 text-left">
                                                <a class="btn btn-success"><b><?php echo $this->arrCategoryParent['cate_name']; ?></b></a>
                                            </div>
                                            <div class="col-md-3 text-right">
                                                <select class="form-control change-location">
                                                    <?php
                                                    $arrLocation = unserialize(ARR_DISTRICT);
                                                    $propSlectName = 'tat-ca';
                                                    $propSlectId = 0;
                                                    if (!empty($this->params['propId'])) {
                                                        $propSlectName = $this->arrPropertiesList[$this->params['propId']]['prop_slug'];
                                                        $propSlectId = $this->arrPropertiesList[$this->params['propId']]['prop_id'];
                                                    }
                                                    ?>
                                                    <option value="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'propSlug' => $propSlectName, 'propId' => $propSlectId]) ?>">Toàn tỉnh</option>
                                                    <?php
                                                    foreach ($arrLocation as $district):
                                                        ?>
                                                        <option value="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $district['dist_slug'], 'distId' => $district['dist_id'], 'propSlug' => $propSlectName, 'propId' => $propSlectId]) ?>"<?php if ($params['distId'] == $district['dist_id']): ?>selected<?php endif; ?>><?php echo $district['dist_name']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-12 border-buttom">
                                            <div class="col-md-12">
                                                <a class="btn <?php if ($this->arrCategoryDetail['parent_id'] == 0): ?>btn-info<?php endif; ?> btn-xs" style="margin-bottom: 3px; margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]); ?>">
                                                    Tất cả
                                                </a>
                                                <?php foreach ($this->arrCategoryChildren as $cate): ?>
                                                    <a class="btn <?php if ($this->arrCategoryDetail['cate_id'] == $cate['cate_id']): ?>btn-info<?php endif; ?> btn-xs" style="margin-bottom: 3px; margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate['cate_slug'], 'cateId' => $cate['cate_id']]); ?>">
                                                        <?php echo $cate['cate_name']; ?>
                                                    </a>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                        <hr/>
                                        <?php if (!empty($this->arrPropertiesList)): ?>
                                            <div class="col-md-12" style="margin-bottom: 10px">
                                                <div class="col-md-12">
                                                    <?php
                                                    $distSlectName = 'toan-tinh';
                                                    $distSlectId = 0;
                                                    if (!empty($this->params['distId'])) {
                                                        $distSlectName = $arrLocation[$this->params['distId']]['dist_slug'];
                                                        $distSlectId = $arrLocation[$this->params['distId']]['dist_id'];
                                                    }
                                                    ?>
                                                    <a class="btn <?php if (empty($this->params['propId'])): ?>btn-warning<?php endif; ?> btn-xs" style="margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $distSlectName, 'distId' => $distSlectId]) ?>">
                                                        Tất cả
                                                    </a>
                                                    <?php
                                                    foreach ($this->arrPropertiesList as $prop):
                                                        ?>
                                                        <a class="btn <?php if (!empty($this->params['propId']) && $this->params['propId'] == $prop['prop_id']): ?>btn-warning<?php endif; ?> btn-xs" style="margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $distSlectName, 'distId' => $distSlectId, 'propSlug' => $prop['prop_slug'], 'propId' => $prop['prop_id']]) ?>">
                                                            <?php echo $prop['prop_name']; ?>
                                                        </a>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </section><!--end main page heading-->
                            <section class="panel">
                                <div class="panel-body" style="padding: 0px">    
                                    <div class="adv-table editable-table">
                                        <section id="unseen">
                                            <table class="table table-hover table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th class="text-center color-title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> Tiêu đề</th>
                                                        <th class="text-center color-location" width="100px"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                                        <?php if (!empty($this->arrPropertiesList)): ?><th class="text-center color-properties hidden-xs" width="85px"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th><?php endif; ?>
                                                        <th class="text-center hidden-xs" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    if ($this->arrContentList):
                                                        foreach ($this->arrContentList as $arrContent):
                                                            $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                                            $flag = false;
                                                            if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                                $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                                $flag = true;
                                                            }
                                                            $description = (strlen($arrContent['cont_detail_text']) > 400) ? substr($arrContent['cont_detail_text'], 0, 400) . '...' : $arrContent['cont_detail_text'];
                                                            ?>
                                                            <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                                <td style="vertical-align: middle">
                                                                    <?php if ($flag == true): ?>
                                                                        <a class="hidden-xs" style="text-decoration: none" href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                                            <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                                        </a>
                                                                    <?php else: ?>
                                                                        <a class="hidden-xs" style="text-decoration: none" href="javascript:;" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                                            <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                                        </a>
                                                                    <?php endif; ?>
                                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip <?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?>vip2<?php elseif ($arrContent['vip_type'] == \My\General::VIP_ALL_PAGE):; ?> color-red<?php endif;?>" style="text-decoration: none;">
                                                                        <?php echo $arrContent['cont_title']; ?>
                                                                    </a>

                                                                    <span class="success">(<i class="fa fa-eye"> <?php echo (int) $arrContent['cont_views']; ?></i> | <i class="fa fa-comment-o" aria-hidden="true"> <?php echo (int) $arrContent['total_comment']; ?></i>)</span>
                                                                    <?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?><img src="<?php echo \My\General::IMAGE_VIP ?>"><?php elseif ($arrContent['vip_type'] == \My\General::VIP_ALL_PAGE):?><img src="<?php echo \My\General::IMAGE_SVIP ?>"><?php endif;?>
                                                                </td>
                                                                <td class="text-center color-location" style="vertical-align: middle">
                                                                    <?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?>
                                                                </td>
                                                                <?php if (!empty($this->arrPropertiesList)): ?>
                                                                    <td class="text-center color-properties hidden-xs" style="vertical-align: middle">
                                                                        <?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?>
                                                                    </td>
                                                                <?php endif; ?>
                                                                <td class="text-center hidden-xs" style="vertical-align: middle">
                                                                    <?php echo My\General::formatDateString($arrContent['updated_date']); ?>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    <?php else: ?>
                                                        <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào cả.</td></tr>
                                                    <?php endif; ?>
                                                </tbody>
                                            </table>
                                        </section>
                                    </div>
                                    <div>
                                        <?php echo $this->paging; ?>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div><!--end related ads-->
                </div>
            </div>

            <div class="col-md-4">
                <?php echo $this->render('frontend/nav-ads-right'); ?>
            </div>
        </div>
    </div>
</section><!--end details-->
<script>
    Category.index();
</script>