<!--Detail -->
<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <?php if (!empty($this->arrProductVipList)): ?>
                    <div class="ads-detail">
                        <div class="premium-ads-sub">
                            <h4 class="inner-heading">RAO VẶT VÍP TRONG DANH MỤC</h4>
                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th style=" color: #005fcc" class=" col-lg-7"><i class="fa fa-list-alt"></i> Tiêu đề</th>
                                        <th class="text-center"  class="hidden-phone" class=" col-lg-2 text-center" style=" color: #005fcc"><i class="fa fa-map-marker"></i> Khu vực</th>
                                        <th class="text-center"  style=" color: #005fcc" class=" col-lg-1"><i class="fa fa-eye"></i> Xem</th>
                                        <th class="text-center" style=" color: #005fcc"><i class="fa fa-clock-o"></i> Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->arrProductVipList as $value): ?>
                                        <tr>
                                            <td>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value["prod_slug"], 'productId' => $value["prod_id"])) ?>" style=" text-decoration: none"><i class="fa fa-hand-o-right"></i> <?php echo html_entity_decode($value['prod_name']); ?> <image style="width:35px" src="<?php echo ($value['prod_vip'] == 2) ? STATIC_URL . '/f/v1/images/s-vip.gif' : STATIC_URL . '/f/v1/images/vip.png ' ?>"/></a>
                                            </td>
                                            <td class="text-center"><?php echo empty($value['prod_location']) ? 'Toàn tỉnh' : $arrLocation[$value['prod_location']]['dist_name']; ?></td>
                                            <td class="text-center"><span><?php echo $value['prod_viewer']; ?></span></td>
                                            <td class="text-center">
                                                <span><?php echo My\General::formatDateString($value['prod_created']) ?></span>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div> <!--end premium ads-->
                    </div>
                <?php endif; ?>

                <!--Related Ads-->
                <div id="relatedAds">
                    <div class="row">
                        <div class="sidebar">
                            <section class="panel panel-primary">
                                <div class="panel-body" style="padding: 0px">
                                    <div class="row border-buttom">
                                        <div class="col-md-12" style="margin-top: 10px">
                                            <div class="col-md-9 text-left">
                                                <a class="btn btn-success"><b><?php echo $this->arrCategoryParent['cate_name']; ?></b></a>
                                            </div>
                                            <div class="col-md-3 text-right">
                                                <select class="form-control change-location">
                                                    <?php
                                                    $arrLocation = unserialize(ARR_DISTRICT);
                                                    $propSlectName = 'tat-ca';
                                                    $propSlectId = 0;
                                                    if (!empty($this->params['propId'])) {
                                                        $propSlectName = $this->arrPropertiesList[$this->params['propId']]['prop_slug'];
                                                        $propSlectId = $this->arrPropertiesList[$this->params['propId']]['prop_id'];
                                                    }
                                                    ?>
                                                    <option value="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'propSlug' => $propSlectName, 'propId' => $propSlectId]) ?>">Toàn tỉnh</option>
                                                    <?php
                                                    foreach ($arrLocation as $district):
                                                        ?>
                                                        <option value="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $district['dist_slug'], 'distId' => $district['dist_id'], 'propSlug' => $propSlectName, 'propId' => $propSlectId]) ?>"<?php if ($params['distId'] == $district['dist_id']): ?>selected<?php endif; ?>><?php echo $district['dist_name']; ?></option>
                                                    <?php endforeach; ?>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="row">
                                        <div class="col-md-12 border-buttom">
                                            <div class="col-md-12">
                                                <a class="btn <?php if ($this->arrCategoryDetail['parent_id'] == 0): ?>btn-info<?php endif; ?> btn-xs" style="margin-bottom: 3px; margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryParent['cate_slug'], 'cateId' => $this->arrCategoryParent['cate_id']]); ?>">
                                                    Tất cả
                                                </a>
                                                <?php foreach ($this->arrCategoryChildren as $cate): ?>
                                                    <a class="btn <?php if ($this->arrCategoryDetail['cate_id'] == $cate['cate_id']): ?>btn-info<?php endif; ?> btn-xs" style="margin-bottom: 3px; margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $cate['cate_slug'], 'cateId' => $cate['cate_id']]); ?>">
                                                        <?php echo $cate['cate_name']; ?>
                                                    </a>
                                                <?php endforeach; ?>
                                            </div>
                                        </div>
                                        <hr/>
                                        <?php if (!empty($this->arrPropertiesList)): ?>
                                            <div class="col-md-12" style="margin-bottom: 10px">
                                                <div class="col-md-12">
                                                    <?php
                                                    $distSlectName = 'toan-tinh';
                                                    $distSlectId = 0;
                                                    if (!empty($this->params['distId'])) {
                                                        $distSlectName = $arrLocation[$this->params['distId']]['dist_slug'];
                                                        $distSlectId = $arrLocation[$this->params['distId']]['dist_id'];
                                                    }
                                                    ?>
                                                    <a class="btn <?php if (empty($this->params['propId'])): ?>btn-warning<?php endif; ?> btn-xs" style="margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $distSlectName, 'distId' => $distSlectId]) ?>">
                                                        Tất cả
                                                    </a>
                                                    <?php
                                                    foreach ($this->arrPropertiesList as $prop):
                                                        ?>
                                                        <a class="btn <?php if (!empty($this->params['propId']) && $this->params['propId'] == $prop['prop_id']): ?>btn-warning<?php endif; ?> btn-xs" style="margin-right: 10px; font-weight: bold" href="<?php echo $this->serverUrl() . $this->Url('category', ['cateSlug' => $this->arrCategoryDetail['cate_slug'], 'cateId' => $this->arrCategoryDetail['cate_id'], 'dist' => $distSlectName, 'distId' => $distSlectId, 'propSlug' => $prop['prop_slug'], 'propId' => $prop['prop_id']]) ?>">
                                                            <?php echo $prop['prop_name']; ?>
                                                        </a>
                                                    <?php endforeach; ?>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </section><!--end main page heading-->
                            <section class="panel">
                                <div class="panel-body" style="padding: 0px">    
                                    <div class="adv-table editable-table">
                                        <section id="unseen">
                                            <table class="table table-hover table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th class="text-center"><i class="fa fa-thumb-tack" aria-hidden="true"></i> Tiêu đề</th>
                                                        <th class="text-center" width="100px"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                                        <?php if (!empty($this->arrPropertiesList)): ?><th class="text-center" width="85px"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th><?php endif; ?>
                                                        <th class="text-center" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    if ($this->arrContentList):
                                                        foreach ($this->arrContentList as $arrContent):
                                                            $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                                            $flag = false;
                                                            if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                                $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                                $flag = true;
                                                            }
                                                            $description = (strlen($arrContent['cont_detail_text']) > 400) ? substr($arrContent['cont_detail_text'], 0, 400) . '...' : $arrContent['cont_detail_text'];
                                                            ?>
                                                            <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                                <td style="vertical-align: middle">
                                                                    <?php if ($flag == true): ?>
                                                                        <a style="text-decoration: none" href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                                            <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                                        </a>
                                                                    <?php else: ?>
                                                                        <a style="text-decoration: none" href="javascript:;" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                                            <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                                        </a>
                                                                    <?php endif; ?>
                                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip vip2" style="text-decoration: none;">
                                                                        <?php echo $arrContent['cont_title']; ?>
                                                                    </a>

                                                                    <span class="color-view">(<i class="fa fa-eye"> <?php echo $arrContent['cont_views']; ?></i>)</span>
                                                                    <?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?><img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif' ?>"><?php endif; ?> <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif' ?>">
                                                                </td>
                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <a href="javascript:;" style="text-decoration: none;color: #69A467"><b><?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $this->arrLocation[$arrContent['dist_id']]['dist_name']; ?></b></a>
                                                                </td>
                                                                <?php if (!empty($this->arrPropertiesList)): ?>
                                                                    <td class="text-center" style="vertical-align: middle">
                                                                        <a href="#" style="text-decoration: none; color: #A94464"><b><?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?></b></a>
                                                                    </td>
                                                                <?php endif; ?>
                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <?php echo My\General::formatDateString($arrContent['created_date']); ?>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    <?php else: ?>
                                                        <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào cả.</td></tr>
                                                    <?php endif; ?>
                                                </tbody>
                                            </table>
                                        </section>
                                    </div>
                                    <div>
                                        <?php echo $this->paging; ?>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div><!--end related ads-->
                    <div class="row">
                        <div class="pagi">
                            <?php echo $this->paging; ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="sidebar">
                    <?php if (!empty($this->arrCategoryChildrenList)): ?>
                        <div class="side-widget clearfix">
                            <h4 class="inner-heading">DANH MỤC CON</h4>
                            <?php foreach ($this->arrCategoryChildrenList as $value): ?>
                                <div class="subcat-widget">
                                    <p><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value["cate_slug"], 'categoryID' => $value["cate_id"])) ?>"><?php echo $value['cate_name']; ?></a></p>
                                    <span><?php echo $value['cate_total_product']; ?></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <!--end premium widget-->


                    <!--advertisement-->
                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>

                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>

                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>
                    <!--end advertisement widget-->

                </div>
            </div>
        </div>
    </div>
</section><!--end details-->
<script>
    Category.index();
</script>