<!--main sub page heading-->
<section id="page-head" class="margin-control">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1><?php echo $this->arrCategoryDetail['cate_name']; ?></h1>
                <h4>Có <?php echo $this->arrCategoryDetail['cate_total_product']; ?> rao vặt trong Danh mục này</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<!--Detail -->
<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <?php if (!empty($this->arrProductVipList)): ?>
                    <div class="ads-detail">
                        <div class="premium-ads-sub">
                            <h4 class="inner-heading">RAO VẶT VÍP TRONG DANH MỤC</h4>
                            <table class="table table-striped table-advance table-hover">
                                <thead>
                                    <tr>
                                        <th style=" color: #005fcc" class=" col-lg-7"><i class="fa fa-list-alt"></i> Tiêu đề</th>
                                        <th class="text-center"  class="hidden-phone" class=" col-lg-2 text-center" style=" color: #005fcc"><i class="fa fa-map-marker"></i> Khu vực</th>
                                        <th class="text-center"  style=" color: #005fcc" class=" col-lg-1"><i class="fa fa-eye"></i> Xem</th>
                                        <th class="text-center" style=" color: #005fcc"><i class="fa fa-clock-o"></i> Cập nhật</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?php foreach ($this->arrProductVipList as $value): ?>
                                        <tr>
                                            <td>
                                                <a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value["prod_slug"], 'productId' => $value["prod_id"])) ?>" style=" text-decoration: none"><i class="fa fa-hand-o-right"></i> <?php echo html_entity_decode($value['prod_name']); ?> <image style="width:35px" src="<?php echo ($value['prod_vip'] == 2) ? STATIC_URL . '/f/v1/images/s-vip.gif' : STATIC_URL . '/f/v1/images/vip.png ' ?>"/></a>
                                            </td>
                                            <td class="text-center"><?php echo empty($value['prod_location']) ? 'Toàn tỉnh' : $arrLocation[$value['prod_location']]['dist_name']; ?></td>
                                            <td class="text-center"><span><?php echo $value['prod_viewer']; ?></span></td>
                                            <td class="text-center">
                                                <span><?php echo My\General::formatDateString($value['prod_created']) ?></span>
                                            </td>
                                        </tr>
                                    <?php endforeach; ?>
                                </tbody>
                            </table>
                        </div> <!--end premium ads-->
                    </div>
                <?php endif; ?>
                <!--                <div class="row">
                                <div class="col-lg-12">
                                    <section class="panel">-->
                <!--                        
                                    </section>
                                </div>
                            </div>-->

                <!--Related Ads-->
                <div id="relatedAds">
                    <h4 class="inner-heading">DANH SÁCH RAO VẶT</h4>
                    <?php if (!empty($this->arrProperties)): ?>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="ad-tabs">
                                    <span class="tab <?php if (empty($this->params['properties'])) : ?> active<?php endif; ?>">Tất cả</span>
                                    <?php foreach ($this->arrProperties as $value): ?>
                                        <span class="tab"><?php echo html_entity_decode($value['prop_name']); ?></span>
                                    <?php endforeach; ?>
                                </div>
                            </div>
                        </div>
                    <?php endif; ?>
                    <div class="row">
                        <table class="table table-striped table-advance table-hover">
                            <thead>
                                <tr>
                                    <th style=" color: #005fcc" class=" col-lg-7"><i class="fa fa-list-alt"></i> Tiêu đề</th>
                                    <th class="text-center"  class="hidden-phone" class=" col-lg-2 text-center" style=" color: #005fcc">Khu vực</th>
                                    <th class="text-center"  style=" color: #005fcc" class=" col-lg-1"> Xem</th>
                                    <th class="text-center"  style=" color: #005fcc" class=" col-lg-1">Nhu cầu</th>
                                    <th class="text-center" style=" color: #005fcc">Cập nhật</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php foreach ($this->arrProductList as $value): ?>
                                    <tr>
                                        <td>
                                            <a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $value["prod_slug"], 'productId' => $value["prod_id"])) ?>" style=" text-decoration: none"><i class="fa fa-hand-o-right"></i> <?php echo html_entity_decode($value['prod_name']); ?> </a>
                                        </td>
                                        <td class="text-center"><?php echo empty($value['prod_location']) ? 'Toàn tỉnh' : $arrLocation[$value['prod_location']]['dist_name']; ?></td>
                                        <td class="text-center"><?php echo $value['prod_viewer']?></td>
                                        <td class="text-center"><span><?php echo $this->arrProperties[$value['prop_id']]['prop_name'];?></span></td>
                                        <td class="text-center">
                                            <span><?php echo My\General::formatDateString($value['prod_created']) ?></span>
                                        </td>
                                    </tr>
                                <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div><!--end related ads-->
                    <div class="row">
                        <div class="pagi">
                            <?php echo $this->paging; ?>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="sidebar">
                    <?php if (!empty($this->arrCategoryChildrenList)): ?>
                        <div class="side-widget clearfix">
                            <h4 class="inner-heading">DANH MỤC CON</h4>
                            <?php foreach ($this->arrCategoryChildrenList as $value): ?>
                                <div class="subcat-widget">
                                    <p><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categorySlug' => $value["cate_slug"], 'categoryID' => $value["cate_id"])) ?>"><?php echo $value['cate_name']; ?></a></p>
                                    <span><?php echo $value['cate_total_product']; ?></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>
                    <!--end premium widget-->


                    <!--advertisement-->
                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>

                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>

                    <div class="side-widget">
                        <h4 class="inner-heading">BANNER</h4>
                        <div class="side-widget-adv">
                            <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/advertiseimg_03.png" alt="google ads"></a>
                        </div>
                    </div>
                    <!--end advertisement widget-->

                </div>
            </div>
        </div>
    </div>
</section><!--end details-->