<?php
    $categoryList = unserialize(ARR_CATEGORY);
?>
<?php if (!empty($this->arrContentList)): ?>
    <section id="premium">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="main-heading mg-bt-15 text-center">
                        <h2>NỔI BẬT</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <section class="panel">
                    <div class="panel-body" style="padding: 0px">    
                        <div class="adv-table editable-table">
                            <section id="unseen">
                                <table class="table table-hover table-striped table-condensed cf">
                                    <thead class="cf">
                                        <tr>
                                            <th class="text-center color-title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> Tiêu đề</th>
                                            <th class="text-center color-location hidden-xs" width="100px"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                            <th class="text-center color-properties hidden-xs" width="85px"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th>
                                            <th class="text-center hidden-xs" width="93px"><i class="fa fa-calendar-o" aria-hidden="true"></i> Cập nhật</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if ($this->arrContentList):
                                            $arrLocation = unserialize(ARR_DISTRICT);
                                            foreach ($this->arrContentList as $arrContent):
                                                $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                                $flag = false;
                                                if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                    $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                    $flag = true;
                                                }
                                                $description = (strlen(html_entity_decode($arrContent['cont_detail_text'])) > 400) ? substr(html_entity_decode($arrContent['cont_detail_text']), 0, 400) . '...' : html_entity_decode($arrContent['cont_detail_text']);
                                                ?>
                                                <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                    <td style="vertical-align: middle">
                                                        <?php if ($flag == true): ?>
                                                            <a class="hidden-xs" style="text-decoration: none" href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                                <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                            </a>
                                                        <?php else: ?>
                                                            <a class="hidden-xs" style="text-decoration: none" href="javascript:;" class="red-tooltip" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                                <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                            </a>
                                                        <?php endif; ?>
                                                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip color-red mg-r-5" style="text-decoration: none;">
                                                            <b><?php echo $arrContent['cont_title']; ?></b>
                                                        </a>
                                                        <span>(<i class="fa fa-eye"> <?php echo (int)$arrContent['cont_views']; ?></i> | <i class="fa fa-comment-o" aria-hidden="true"> <?php echo (int)$arrContent['total_comment']; ?></i>)</span>
                                                        <img src="<?php echo \My\General::IMAGE_SVIP ?>">
                                                    </td>
                                                    <td class="text-center color-location hidden-xs" style="vertical-align: middle">
                                                        <?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?>
                                                    </td>
                                                    <td class="text-center color-properties hidden-xs" style="vertical-align: middle">
                                                        <?php echo !empty($this->arrPropertiesList[$arrContent['prop_id']]['prop_name']) ? $this->arrPropertiesList[$arrContent['prop_id']]['prop_name'] : $categoryList[$arrContent['cate_id']]['cate_name'] ; ?>
                                                    </td>
                                                    <td class="text-center hidden-xs" style="vertical-align: middle">
                                                        <?php echo My\General::formatDateString($arrContent['updated_date']); ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào cả.</td></tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </section>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section><!--End Premium Advertisement-->
<?php endif; ?>

<!--Category-->
<!--<div align="center">-->
<!--    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>-->
<!--    <!-- Ads top -->-->
<!--    <ins class="adsbygoogle"-->
<!--         style="display:inline-block;width:728px;height:90px"-->
<!--         data-ad-client="ca-pub-4608570842050780"-->
<!--         data-ad-slot="6344671952"></ins>-->
<!--    <script>-->
<!--        (adsbygoogle = window.adsbygoogle || []).push({});-->
<!--    </script>-->
<!--</div>-->
<section id="categories">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="main-heading text-center">
                    <h2>DANH MỤC</h2>
                </div>
            </div>
        </div>
        <?php if (!empty($this->arrCategoryParentList)): ?>
            <div class="row">
                <?php
                $i = 0;
                $total = count($this->arrCategoryParentList);
                foreach ($this->arrCategoryParentList as $value):
                    if ($i == 0 || ($i % 4 == 0)):
                        ?>
                        <div class="row">
                        <?php endif; ?>

                        <div class="col-md-3 col-sm-6">
                            <div class="category">
                                <div class="category-icon">
                                    <i class="fa <?php echo str_replace('icon', 'fa', $value['cate_icon']); ?> fa-2x"></i>
                                </div>
                                <h4><a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $value["cate_slug"], 'cateId' => $value["cate_id"])) ?>"><?php echo mb_strtoupper($value['cate_name']); ?></a></h4>
                                <?php
                                if (!empty($arrCategoryByParent[$value['cate_id']])):
                                    foreach ($arrCategoryByParent[$value['cate_id']] as $valueChildren):
                                        ?>
                                        <p><a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $valueChildren["cate_slug"], 'cateId' => $valueChildren["cate_id"])) ?>"><?php echo $valueChildren['cate_name']; ?>  ( <?php echo (int) $valueChildren['total_content']; ?> )</a></p>
                                        <?php
                                    endforeach;
                                endif;
                                ?>
                            </div>
                        </div>

                        <?php if ($i != 0 && (((($i + 1) % 4 ) == 0) || ($i == $total - 1))): ?>
                        </div>
                    <?php endif; ?>

                    <?php
                    $i++;
                endforeach;
                ?>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-12">
                <div class="advertise">
                    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
                    <!-- Ads top -->
                    <ins class="adsbygoogle"
                         style="display:inline-block;width:728px;height:90px"
                         data-ad-client="ca-pub-4608570842050780"
                         data-ad-slot="6344671952"></ins>
                    <script>
                        (adsbygoogle = window.adsbygoogle || []).push({});
                    </script>
<!--                    <a href="#"><img src="--><?php //echo STATIC_URL; ?><!--/f/v1/images/images/ad_03.png" alt="ad"> </a>-->
                </div>
            </div>
        </div>
    </div>
</section><!--End Category-->

<!--Classify Advertisement-->
<section id="advertisement">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 border-buttom">
                <div class="main-heading-title text-center">
                    <h3>RAO VẶT MỚI</h3>
                </div>

            </div>
            <?php if (!empty($this->arrNewContentList)):
                ?>
                <section class="panel">
                    <div class="panel-body" style="padding: 0px">    
                        <div class="adv-table editable-table">
                            <section id="unseen">
                                <table class="table table-hover table-striped table-condensed cf">
                                    <thead class="cf">
                                        <tr>
                                            <th class="text-center color-title"><i class="fa fa-bookmark-o" aria-hidden="true"></i> Tiêu đề</th>
                                            <th class="text-center color-location hidden-xs" width="100px"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                            <th class="text-center color-properties hidden-xs" width="85px"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th>
                                            <th class="text-center hidden-xs" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $arrLocation = unserialize(ARR_DISTRICT);
                                        foreach ($this->arrNewContentList as $arrContent):
                                            $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                            $flag = false;
                                            if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                $flag = true;
                                            }
                                            $description = (strlen(html_entity_decode($arrContent['cont_detail_text'])) > 400) ? substr(html_entity_decode($arrContent['cont_detail_text']), 0, 400) . '...' : html_entity_decode($arrContent['cont_detail_text']);
                                            ?>
                                            <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                <td style="vertical-align: middle">
                                                    <?php if ($flag == true): ?>
                                                        <a class="hidden-xs" style="text-decoration: none" href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                            <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                        </a>
                                                    <?php else: ?>
                                                        <a class="hidden-xs" style="text-decoration: none" href="javascript:;" class="red-tooltip mg-r-5" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                            <img src="<?php echo $avatar_user; ?>" class="thumb-image-avatar">
                                                        </a>
                                                    <?php endif; ?>
                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip <?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?>vip2<?php endif; ?>" style="text-decoration: none;">
                                                        <?php echo $arrContent['cont_title']; ?>
                                                    </a>

                                                    <span class="success">(<i class="fa fa-eye"> <?php echo (int)$arrContent['cont_views']; ?></i> | <i class="fa fa-comment-o" aria-hidden="true"> <?php echo (int)$arrContent['total_comment']; ?></i>)</span>
                                                    <?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?><img src="<?php echo \My\General::IMAGE_VIP ?>"><?php endif; ?>
                                                </td>
                                                <td class="text-center color-location hidden-xs" style="vertical-align: middle">
                                                    <?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?>
                                                </td>
                                                <td class="text-center color-properties hidden-xs" style="vertical-align: middle">
                                                    <?php echo !empty($this->arrPropertiesList[$arrContent['prop_id']]['prop_name']) ? $this->arrPropertiesList[$arrContent['prop_id']]['prop_name'] : $categoryList[$arrContent['cate_id']]['cate_name'] ; ?>
                                                </td>
                                                <td class="text-center hidden-xs" style="vertical-align: middle">
                                                    <?php echo My\General::formatDateString($arrContent['created_date']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </section>
                        </div>
                        <div>
                            <?php echo $this->paging; ?>
                        </div>
                    </div>
                </section>
            <?php endif; ?>
        </div>
    </div>
</section>