<?php
$arrCategoryListChildrenFormat = $this->arrCategoryListChildrenFormat;
?>
<?php if (!empty($this->arrContentList)): ?>
    <section id="premium">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="main-heading mg-bt-15 text-center">
                        <h2>NỔI BẬT</h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <section class="panel">
                    <div class="panel-body" style="padding: 0px">    
                        <div class="adv-table editable-table">
                            <section id="unseen">
                                <table class="table table-hover table-striped table-condensed cf">
                                    <thead class="cf">
                                        <tr>
                                            <th class="text-center" style="color: #337ab7"><i class="fa fa-thumb-tack" aria-hidden="true"></i> Tiêu đề</th>
                                            <th class="text-center" width="100px" style="color: #69A467"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                            <th class="text-center" width="85px" style="color: #A94464"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th>
                                            <th class="text-center" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if ($this->arrContentList):
                                            $arrLocation = unserialize(ARR_DISTRICT);
                                            foreach ($this->arrContentList as $arrContent):
                                                $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                                $flag = false;
                                                if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                    $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                    $flag = true;
                                                }
                                                $description = (strlen($arrContent['cont_detail_text']) > 400) ? substr($arrContent['cont_detail_text'], 0, 400) . '...' : $arrContent['cont_detail_text'];
                                                ?>
                                                <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                    <td style="vertical-align: middle">
                                                        <div class="col-md-1">
                                                            <?php if ($flag == true): ?>
                                                                <a href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                                    <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                                </a>
                                                            <?php else: ?>
                                                                <a href="javascript:;" class="red-tooltip" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                                    <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                                </a>
                                                            <?php endif; ?>
                                                        </div>
                                                        <div class="col-md-11" style="margin-top: 5px;">
                                                            <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip color-red" style="text-decoration: none;">
                                                                <b><?php echo $arrContent['cont_title']; ?></b>
                                                            </a>
                                                            <span class="color-view">(<i class="fa fa-eye"> <?php echo $arrContent['cont_views']; ?></i>)</span>
                                                            <img src="<?php echo STATIC_URL . '/f/v1/images/s-vip.gif'; ?>">
                                                        </div>
                                                    </td>
                                                    <td class="text-center" style="vertical-align: middle">
                                                        <a href="javascript:;" style="text-decoration: none;color: #69A467"><b><?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?></b></a>
                                                    </td>
                                                    <td class="text-center" style="vertical-align: middle">
                                                        <a href="#" style="text-decoration: none; color: #A94464"><b><?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?></b></a>
                                                    </td>
                                                    <td class="text-center" style="vertical-align: middle">
                                                        <?php echo My\General::formatDateString($arrContent['created_date']); ?>
                                                    </td>
                                                </tr>
                                            <?php endforeach; ?>
                                        <?php else: ?>
                                            <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào cả.</td></tr>
                                        <?php endif; ?>
                                    </tbody>
                                </table>
                            </section>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section><!--End Premium Advertisement-->
<?php endif; ?>

<!--Category-->
<section id="categories">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="main-heading text-center">
                    <h2>DANH MỤC</h2>
                </div>
            </div>
        </div>
        <?php if (!empty($this->arrCategoryParentList)): ?>
            <div class="row">
                <?php foreach ($this->arrCategoryParentList as $value): ?>
                    <div class="col-md-3 col-sm-6">
                        <div class="category">
                            <div class="category-icon">
                                <i class="fa <?php echo str_replace('icon', 'fa', $value['cate_icon']); ?> fa-2x"></i>
                            </div>
                            <h4><a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $value["cate_slug"], 'cateId' => $value["cate_id"])) ?>"><?php echo mb_strtoupper($value['cate_name']); ?></a></h4>
                            <?php
                            if (!empty($arrCategoryByParent[$value['cate_id']])):
                                foreach ($arrCategoryByParent[$value['cate_id']] as $valueChildren):
                                    ?>
                                    <p><a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $valueChildren["cate_slug"], 'cateId' => $valueChildren["cate_id"])) ?>"><?php echo $valueChildren['cate_name']; ?>  ( <?php echo (int) $valueChildren['total_content']; ?> )</a></p>
                                    <?php
                                endforeach;
                            endif;
                            ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <div class="row">
            <div class="col-md-12">
                <div class="advertise">
                    <a href="#"><img src="<?php echo STATIC_URL; ?>/f/v1/images/images/ad_03.png" alt="ad"> </a>
                </div>
            </div>
        </div>
    </div>
</section><!--End Category-->

<!--Classify Advertisement-->
<section id="advertisement">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 border-buttom">
                <div class="main-heading-title text-center">
                    <h3>RAO VẶT MỚI</h3>
                </div>

            </div>
            <?php if (!empty($this->arrNewContentList)):
                ?>
                <section class="panel">
                    <div class="panel-body" style="padding: 0px">    
                        <div class="adv-table editable-table">
                            <section id="unseen">
                                <table class="table table-hover table-striped table-condensed cf">
                                    <thead class="cf">
                                        <tr>
                                            <th class="text-center" style="color: #337ab7"><i class="fa fa-thumb-tack" aria-hidden="true"></i> Tiêu đề</th>
                                            <th class="text-center" width="100px" style="color: #69A467"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                            <th class="text-center" width="85px" style="color: #A94464"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th>
                                            <th class="text-center" width="57px" style="color: #1b95e0"><i class="fa fa-eye" aria-hidden="true"></i> Xem</th>
                                            <th class="text-center" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        $arrLocation = unserialize(ARR_DISTRICT);
                                        foreach ($this->arrNewContentList as $arrContent):
                                            $avatar_user = STATIC_URL . '/f/v1/images/icon.png';
                                            $flag = false;
                                            if (!empty($arrContent['user_created']) && !empty($this->arrUserList[$arrContent['user_created']]['user_avatar'])) {
                                                $avatar_user = json_decode($this->arrUserList[$arrContent['user_created']]['user_avatar'], true)[0]['thumbImage']['30x30'];
                                                $flag = true;
                                            }
                                            $description = (strlen($arrContent['cont_detail_text']) > 400) ? substr($arrContent['cont_detail_text'], 0, 400) . '...' : $arrContent['cont_detail_text'];
                                            ?>
                                            <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                <td style="vertical-align: middle">
                                                    <!--<div class="col-md-1 col-sm-0">-->
                                                        <?php if ($flag == true): ?>
                                                            <a href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>" class="red-tooltip" data-toggle="tooltip" title="<?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?>">
                                                                <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                            </a>
                                                        <?php else: ?>
                                                            <a href="javascript:;" class="red-tooltip" data-toggle="tooltip" title="<?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?>">
                                                                <img src="<?php echo $avatar_user; ?>" style="width: 30px; height: 30px">
                                                            </a>
                                                        <?php endif; ?>
                                                    <!--</div>-->
                                                    <!--<div class="col-md-11 col-xs-12" style="margin-top: 5px;">-->
                                                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $description; ?>" class="red-tooltip vip2" style="text-decoration: none;">
                                                            <?php echo $arrContent['cont_title']; ?><?php if ($arrContent['vip_type'] == \My\General::VIP_CATE_PAGE): ?><img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif' ?>"><?php endif; ?> <img src="<?php echo STATIC_URL . '/f/v1/images/vip2.gif' ?>">
                                                        </a>
                                                    <!--</div>-->
                                                </td>
                                                <td class="text-center" style="vertical-align: middle">
                                                    <a href="javascript:;" style="text-decoration: none;color: #69A467"><b><?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?></b></a>
                                                </td>
                                                <td class="text-center" style="vertical-align: middle">
                                                    <a href="javascript:;" style="text-decoration: none; color: #A94464"><b><?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?></b></a>
                                                </td>

                                                <td class="text-center" style="vertical-align: middle;color: #1b95e0">
                                                    <?php echo $arrContent['cont_views']; ?>
                                                </td>
                                                <td class="text-center" style="vertical-align: middle">
                                                    <?php echo My\General::formatDateString($arrContent['created_date']); ?>
                                                </td>
                                            </tr>
                                        <?php endforeach; ?>
                                    </tbody>
                                </table>
                            </section>
                        </div>
                        <div>
                            <?php echo $this->paging; ?>
                        </div>
                    </div>
                </section>
            <?php endif; ?>
        </div>
    </div>
</section>