<head>
    <title>Siêu thị sống khỏe &amp; đẹp online | Megavita Việt Nam - Archive</title>        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="content-language" content="vi" />
    <!--<meta name="robots" content="INDEX, FOLLOW" />-->
    <meta http-equiv="Expires" content="0" />
    <meta name='revisit-after' content='1 days' />
    <meta http-equiv="REFRESH" content="1200" />
    <meta property="article:author" content="https://www.facebook.com/megavita.vn" />
    <meta name="keywords" content="megavita, suc khoe, lam dep, online, mua sam, truc tiep, gia re">
    <meta name="description" content="Megavita cung cấp mỹ phẩm, thực phẩm chức năng với số lượng &amp; chủng loại đa dạng nhất Việt Nam, đáp ứng trọn vẹn mọi nhu cầu về làm đẹp và sức khỏe.">
</head>
<body>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'category')) ?>">Danh mục</a><br/>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'tags')) ?>">Tags Sản phẩm</a></br>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'tags-content')) ?>">Tags Bài viết</a></br>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'brand')) ?>">Thương hiệu</a></br>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'product')) ?>">Sản phẩm</a></br>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'content')) ?>">Bài viết</a><br/>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'keyword')) ?>">Keyword</a><br/>
    <a href="<?php echo $this->serverUrl() . $this->Url('sitemap', array('controller' => 'sitemap', 'action' => 'other')) ?>">Other</a>
</body>