<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>ĐỔI MẬT KHẨU</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <?php if ($this->errors): ?>
                <div class="alert alert-block alert-danger fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-exclamation-triangle"></i> Lỗi!</h4>
                    <?php foreach ($this->errors as $error): ?>
                        <p> - <?php echo $error; ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if ($this->flashMessenger()->setNamespace('change-pass-success')->getMessages()):
                ?>
                <div class="alert alert-success alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-thumbs-o-up"></i> Hoàn tất!</h4>
                    <p>- <?php echo $this->flashMessenger()->setNamespace('change-pass-success')->getMessages()[0]; ?></p>
                </div>
            <?php endif; ?>

            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-5">
                        <div class="ads-detail">
                            <div class="account-overview">
                                <div class="row">
                                    <div class="col-md-12 border-detail">
                                        <div id="form">
                                            <form method="post">
                                                <div class="col-md-12 form-group">
                                                    <input type="password" class="form-group" name="old_password" placeholder="Nhập mật khẩu cũ">
                                                </div>
                                                <div class="col-md-12 form-group">
                                                    <input type="password" class="form-group" name="new_password" placeholder="Nhập mật khẩu mới">
                                                </div>
                                                <div class="col-md-12 form-group">
                                                    <input type="password" class="form-group" name="re_new_password" placeholder="Nhập lại mật khẩu mới">
                                                </div>
                                                <div class="col-md-2 col-xs-offset-6 col-md-offset-8">
                                                 <button type="submit" class="btn btn-primary">Xác nhận</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->render('frontend/nav-ads-right'); ?>
                    </div>
                </div>
            </div>
        </section><!--end details-->
    </div>
</section>
<script>
</script>