<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>Đổi mật khẩu</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <?php if ($this->errors): ?>
                <div class="alert alert-block alert-danger fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-exclamation-triangle"></i> Lỗi!</h4>
                    <?php foreach ($this->errors as $error): ?>
                        <p> - <?php echo $error; ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if ($this->success):
                ?>
                <div class="alert alert-success alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-thumbs-o-up"></i> Hoàn tất!</h4>
                    <p>- <?php echo $this->success; ?></p>
                </div>
            <?php endif; ?>

            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-6">
                        <div class="ads-detail">
                            <div class="account-overview">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div id="form">
                                            <form method="post">
                                                <div class="row form-group">
                                                    <input type="password" class="form-group" name="old_password" placeholder="Nhập mật khẩu cũ">
                                                </div>
                                                <div class="row form-group">
                                                    <input type="password" class="form-group" name="new_password" placeholder="Nhập mật khẩu mới">
                                                </div>
                                                <div class="row form-group">
                                                    <input type="password" class="form-group" name="re_new_password" placeholder="Nhập lại mật khẩu mới">
                                                </div>
                                                <button type="submit" class="btn btn-primary pull-right">Xác nhận</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <?php echo $this->render('frontend/nav-ads-right'); ?>
                    </div>
                </div>
            </div>
        </section><!--end details-->
    </div>
</section>
<script>
</script>