<!--main sub page heading-->
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>LỖI</h1>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<!--Detail -->
<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="notification">
                    <div class="notification-box">

                        <div class="note-box alert-danger">
                            <i class="fa fa-remove"></i>
                            <p>Xảy ra lỗi trong quá trình kết nối với ! Vui lòng thử lại sau giây lát!</p>
                        </div>
                    </div>

                    <div class="listing">
                        <h4 class="inner-heading">LISTINGS</h4>

                        <div class="row">
                            <div class="col-md-6">
                                <ul>
                                    <li>
                                        <i class="fa fa-angle-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6 left-padding-control">
                                <ul>
                                    <li>
                                        <i class="fa fa-check"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-check"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-check"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-check"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-check"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6">
                                <ul>
                                    <li>
                                        <i class="fa fa-angle-double-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-double-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-double-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-double-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-angle-double-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                </ul>
                            </div>
                            <div class="col-md-6 left-padding-control">
                                <ul>
                                    <li>
                                        <i class="fa fa-caret-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-caret-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-caret-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-caret-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                    <li>
                                        <i class="fa fa-caret-right"></i>
                                        <span>Mirum est notare quam littera gothica, quam nuncet</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <?php echo $this->render('frontend/nav-ads-right'); ?>
            </div>
        </div>
    </div>
</section><!--end details-->