<?php
$arrDetailUser = $this->arrDetailUser;
$avatar = empty($arrDetailUser['user_avatar']) ? STATIC_URL . '/f/v1/images/no_avatar_male.jpg' : json_decode($arrDetailUser['user_avatar'], true)[0]['thumbImage']['150x150'];
?>
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>THÔNG TIN CÁ NHÂN</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <?php if ($this->errors): ?>
                <div class="alert alert-block alert-danger fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-exclamation-triangle"></i> Lỗi!</h4>
                    <?php foreach ($this->errors as $error): ?>
                        <p> - <?php echo $error; ?></p>
                    <?php endforeach; ?>
                </div>
            <?php endif; ?>

            <?php
            if ($this->flashMessenger()->setNamespace('edit-info-success')->getMessages()):
                ?>
                <div class="alert alert-success alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-thumbs-o-up"></i> Hoàn tất!</h4>
                    <p>- <?php echo $this->flashMessenger()->setNamespace('edit-info-success')->getMessages()[0]; ?></p>
                </div>
            <?php endif; ?>

            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-5">
                        <div class="ads-detail">
                            <div class="account-overview">
                                <div class="row">
                                    <div class="col-md-12 border-detail">
                                        <div id="form">
                                            <form method="post">
                                                <div class="row">
                                                    <div class="col-md-4 padding-control">
                                                        <div class="img-prod">
                                                            <img class="prod-images" src="<?php echo $avatar; ?>"><br/>
                                                            <div class="pull-right">
                                                                <a class="tooltips edit pull-left" title="Chọn ảnh đại điện khác" data-toggle="tooltip"><i class="fa fa-upload" aria-hidden="true"></i></a>  
                                                                <input type="file" style="display: none">
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-8">
                                                        <div class="col-md-5 form-group"><b>Họ và tên</b></div>
                                                        <div class="col-md-7 form-group"><?php echo $arrDetailUser['user_fullname']; ?></div>
                                                        <div class="col-md-5 form-group"><b>Email</b></div>
                                                        <div class="col-md-7 form-group"><?php echo $arrDetailUser['user_email']; ?></div>
                                                        <div class="col-md-5 form-group"><b>Số điện thoại</b></div>
                                                        <div class="col-md-7 form-group"><?php echo $arrDetailUser['user_phone']; ?></div>
                                                        <div class="col-md-5 form-group"><b>Số dư</b></div>
                                                        <div class="col-md-7 form-group"><b class="color-red"><?php echo number_format($arrDetailUser['user_balance'],0,",","."); ?> đ</b></div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Họ và Tên</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_fullname" value="<?php echo $arrDetailUser['user_fullname']; ?>"></div>
                                                    </div>
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Email</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_email" value="<?php echo $arrDetailUser['user_email']; ?>"></div>
                                                    </div>
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Di động</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_phone" value="<?php echo $arrDetailUser['user_phone']; ?>"></div>
                                                    </div>
                                                </div>
                                                <div class="col-md-2 col-xs-offset-6 col-md-offset-8">
                                                    <button type="submit" class="btn btn-primary">Xác nhận</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <?php echo $this->render('frontend/nav-ads-right'); ?>
                    </div>
                </div>
            </div>
        </section><!--end details-->
    </div>
</section>
<script>
    changeAvatarURL = '<?php echo $this->serverUrl() . $this->Url('user-change-avatar'); ?>';
    User.index();
</script>