<?php
$arrDetailUser = $this->arrDetailUser;
$avatar = empty($arrDetailUser['user_avatar']) ? STATIC_URL . '/f/v1/images/no_avatar_male.jpg' : '';
?>
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>Thông tin cá nhân</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <?php if ($this->errors): ?>
                <div class="alert alert-block alert-danger fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-exclamation-triangle"></i> Lỗi!</h4>
                    <?php foreach($this->errors as $error):?>
                    <p> - <?php echo $error; ?></p>
                    <?php endforeach;?>
                </div>
            <?php endif; ?>

            <?php
            if ($this->success):
                ?>
                <div class="alert alert-success alert-block fade in">
                    <button class="close close-sm" type="button" data-dismiss="alert">
                        <i class="fa fa-times-circle"></i>
                    </button>
                    <h4><i class="fa fa-thumbs-o-up"></i> Hoàn tất!</h4>
                    <p>- <?php echo $this->success; ?></p>
                </div>
            <?php endif; ?>

            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-6">
                        <div class="ads-detail">
                            <div class="account-overview">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div id="form">
                                            <form method="post">
                                                <div class="row">
                                                    <div class="col-md-4 padding-control">
                                                        <div class="img-prod">
                                                            <img class="prod-images" src="<?php echo $avatar; ?>"><br/>
                                                            <div class="pull-right">
                                                                <a class="tooltips edit pull-left" title="Chọn ảnh đại điện khác" data-toggle="tooltip"><i class="fa fa-upload" aria-hidden="true"></i></a>  
                                                                <a target="_bank" href="<?php echo $avatar; ?>" class="tooltips view-images" data-placement="top" data-original-title="Xem"><i class="fa fa-search"></i></a>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-md-8" style="overflow: hidden;">
                                                        <div class="dl-horizontal">
                                                            <dt>Tên:</dt>
                                                            <dd><?php echo $arrDetailUser['user_fullname']; ?></dd>
                                                            <dt>Email :</dt>
                                                            <dd><?php echo $arrDetailUser['user_email']; ?></dd>
                                                            <dt>Di động :</dt>
                                                            <dd><?php echo $arrDetailUser['user_phone']; ?></dd>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Họ và Tên</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_fullname" value="<?php echo $arrDetailUser['user_fullname']; ?>"></div>
                                                    </div>
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Email</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_email" value="<?php echo $arrDetailUser['user_email']; ?>"></div>
                                                    </div>
                                                    <div class="col-md-12 form-group">
                                                        <div class="col-md-3"><b class="form-group">Di động</b></div>
                                                        <div class="col-md-9"><input class="form-group" name="user_phone" value="<?php echo $arrDetailUser['user_phone']; ?>"></div>
                                                    </div>
                                                </div>
                                                <button type="submit" class="btn btn-primary pull-right">Thay đổi</button>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <?php echo $this->render('frontend/nav-ads-right'); ?>
                    </div>
                </div>
            </div>
        </section><!--end details-->
    </div>
</section>
<script>
</script>