<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>Danh sách tin nhắn</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-9">
                        <div> </div>
                        <div class="sidebar">
                            <aside class="lg-side">
                                <div class="inbox-body">
                                    <table class="table table-inbox table-hover">
                                        <thead class="">
                                            <tr>
                                                <td class="text-center" width="60"><input type="checkbox" class="mail-checkbox"><b>All</b></td>
                                                <td colspan="3"><a class="btn btn-danger"><i class="fa fa-trash"></i></a></td>
                                            </tr>
                                            <tr>
                                                <th class="text-center"></th>
                                                <th class="text-center"><i class="fa fa-user"></i> Người gửi</th>
                                                <th class="text-center"><i class="fa fa-envelope-o" aria-hidden="true"></i></i> Nội dung</th>
                                                <th class="text-center"><i class="fa fa-close" aria-hidden="true"></i></i> Gửi lúc</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr class="unread">
                                                <td class="text-center">
                                                    <input type="checkbox" class="mail-checkbox">
                                                </td>
                                                <td class="text-center">Vector Lab</td>
                                                <td class="text-center">Lorem ipsum dolor imit set.</td>
                                                <td class="text-center">9:27 AM</td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                            </aside>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</section><!--end details-->