<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>TÀI KHOẢN </h1>
                <h4>DANH SÁCH RAO VẶT ĐÃ LƯU</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="detail">
    <div class="container">
        <section class="wrapper site-min-height">
            <div class="container">
                <div class="row">
                    <?php echo $this->render('frontend/nav-user-left'); ?>
                    <div class="col-md-9">
                        <div class="sidebar">
                            <section class="panel panel-success">
                                <div class="panel-body">    
                                    <div class="adv-table editable-table ">  
                                        <div class="row" style="margin-bottom: 5px">
                                            <div class="col-lg-4 col-sm-4 col-md-4 col-xs-12">                  
                                                <div id="editable-sample_length" class="dataTables_length no-padding">
                                                    <a class="btn btn-danger btn-sm remove-all" ><i class="fa fa-trash-o"></i> Xóa</a>
                                                </div>
                                            </div>
                                        </div>
                                        <section id="unseen">
                                            <table class="table table-bordered table-hover table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th class="text-center"><input type="checkbox" class="check-all">All</th>
                                                        <th class="text-center"><i class="fa fa-barcode"></i> Mã tin</th>
                                                        <th class="text-center"><i class="fa fa-thumb-tack" aria-hidden="true"></i> Tiêu đề</th>
                                                        <th class="text-center"><i class="fa fa-user"></i> Người đăng</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    if ($this->arrFavouriteList):
                                                        foreach ($this->arrFavouriteList as $arrFavourite):
                                                            ?>
                                                            <tr id="item-<?php echo $arrFavourite['favo_id'] ?>">
                                                                <td class="text-center">
                                                                    <input type="checkbox" class="content-item" value="<?php echo $arrFavourite['favo_id']; ?>">
                                                                </td>
                                                                <td class="text-center">
                                                                    <b>RV<?php echo sprintf("%04d", $arrFavourite['cont_id']); ?></b>
                                                                </td>
                                                                <td style="max-width: 400px">
                                                                    <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $this->arrContentList[$arrFavourite['cont_id']]['cont_slug'], 'contentId' => $arrFavourite['cont_id']]); ?>" style="text-decoration: none">
                                                                        <b><?php echo $this->arrContentList[$arrFavourite['cont_id']]['cont_title']; ?></b>
                                                                    </a>
                                                                </td>
                                                                <td class="text-center">
                                                                    <a href="" style="text-decoration: none">
                                                                        <b><?php echo empty($this->arrContentList[$arrFavourite['cont_id']]['user_created']) ? $this->arrContentList[$arrFavourite['cont_id']]['user_info']['user_fullname'] : $this->arrUserList[$this->arrContentList[$arrFavourite['cont_id']]['user_created']]['user_fullname'] ?></b>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    <?php else: ?>
                                                        <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào trong danh sách.</td></tr>
                                                    <?php endif; ?>
                                                </tbody>
                                            </table>
                                        </section>
                                    </div>
                                    <div>
                                        <?php echo $this->paging; ?>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </section><!--end details-->
    </div>
</section>
<script>
    var deleteSavePostURL = '<?php echo $this->serverUrl() . $this->Url('delete-save-post'); ?>';
    User.listSavePost();
</script>