
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1><?php echo $this->arrUserDetail['user_fullname']; ?></h1>
                <h4>THÀNH VIÊN</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<!--Detail -->
<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <div class="profile-data">
                    <div class="author-contact-detail">
                        <div class="row">
                            <div class="col-md-9 col-sm-9">
                                <h4 class="inner-heading">THÔNG TIN LIÊN HỆ</h4>
                                <div class="author-profile-details">
                                    <ul>
                                        <li>
                                            <i class="fa fa-user"></i>
                                            Họ và tên: <?php echo $this->arrUserDetail['user_fullname']; ?>
                                        </li>
                                        <li>
                                            <i class="fa fa-phone"></i>
                                            Điện thoại: <?php echo $this->arrUserDetail['user_phone']; ?>
                                        </li>
                                        <li>
                                            <i class="fa fa-envelope"></i>
                                            Email: <a href="#" class="col"><?php echo $this->arrUserDetail['user_email']; ?></a>
                                        </li>
                                    </ul>
                                </div>
                            </div>
                            <div class="col-md-3 col-sm-3">
                                <div class="author-avatar-image">
                                    <?php
                                    $avatar = 'http://dev.st.raovat.vn/f/v1/images/noavatar.jpg';
                                    if (!empty($this->arrUserDetail['user_avatar'])) {
                                        $avatar = json_decode($this->arrUserDetail['user_avatar'],true)[0]['thumbImage']['150x150'];
                                    }
                                    ?>
                                    <img src="<?php echo $avatar;?>" alt="author avatar">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <h4 class="inner-heading">DANH SÁCH RAO VẶT ĐÃ ĐĂNG</h4>
                            <section class="panel">
                                <div class="panel-body" style="padding: 0px">    
                                    <div class="adv-table editable-table">
                                        <section id="unseen">
                                            <table class="table table-hover table-striped table-condensed cf">
                                                <thead class="cf">
                                                    <tr>
                                                        <th class="text-center"><i class="fa fa-thumb-tack" aria-hidden="true"></i> Tiêu đề</th>
                                                        <th class="text-center" width="100px"><i class="fa fa fa-globe" aria-hidden="true"></i> Khu vực</th>
                                                        <th class="text-center" width="85px"><i class="fa fa-shopping-cart" aria-hidden="true"></i> Nhu cầu</th>
                                                        <th class="text-center" width="57px"><i class="fa fa-eye" aria-hidden="true"></i> Xem</th>
                                                        <th class="text-center" width="93px"><i class="fa fa-calendar" aria-hidden="true"></i> Cập nhật</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <?php
                                                    if ($this->arrContentList):
                                                        $arrLocation = unserialize(ARR_DISTRICT);
                                                        foreach ($this->arrContentList as $arrContent):
                                                            ?>
                                                            <tr id="item-<?php echo $arrContent['cont_id'] ?>">
                                                                <td style="vertical-align: middle">
                                                                    <div class="col-md-12" style="margin-top: 5px">
                                                                        <a href="<?php echo $this->serverUrl() . $this->Url('view-content', ['contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id']]); ?>" data-toggle="tooltip" title="<?php echo $arrContent['cont_detail_text']; ?>" class="red-tooltip" style="text-decoration: none;">
                                                                            <b><?php echo $arrContent['cont_title']; ?></b>
                                                                        </a>
                                                                    </div>
                                                                </td>
                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <a href="javascript:;" style="text-decoration: none;color: #69A467"><b><?php echo empty($arrContent['dist_id']) ? 'Toàn tỉnh' : $arrLocation[$arrContent['dist_id']]['dist_name']; ?></b></a>
                                                                </td>
                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <a href="#" style="text-decoration: none; color: #A94464"><b><?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?></b></a>
                                                                </td>

                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <?php echo $arrContent['cont_views']; ?>
                                                                </td>
                                                                <td class="text-center" style="vertical-align: middle">
                                                                    <?php echo My\General::formatDateString($arrContent['created_date']); ?>
                                                                </td>
                                                            </tr>
                                                        <?php endforeach; ?>
                                                    <?php else: ?>
                                                        <tr><td colspan="5" class="text-center">Hiện tại chưa chưa có tin rao vặt nào cả.</td></tr>
                                                    <?php endif; ?>
                                                </tbody>
                                            </table>
                                        </section>
                                    </div>
                                    <div>
                                        <?php echo $this->paging; ?>
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <?php echo $this->render('frontend/nav-ads-right'); ?>
            </div>
        </div>
    </div>
</section><!--end details-->

<script>
    var deletePostURL = '<?php echo $this->serverUrl() . $this->Url('delete-content'); ?>';
    User.listPost();
</script>