<?php

use My\General;

$arrPaymentList = General::getPaymentMethod();
?>
<div id="content">
    <div class="block-head">
        <?php
        echo $this->render('frontend/menu');
        ?>
        <div class="breadcrumb">
            <div class="item item-end">
                <div class="ar-right">
                    <div class="cont">
                        <a href="<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'index')); ?>">Danh sách đơn hàng</a>
                    </div>
                </div>
            </div>
            <div class="item  active">
                <div class="ar-right">
                    <div class="cont">
                        <?php echo 'Đơn hàng ' . $this->detailOrder['orde_code'] . $this->detailOrder['orde_id']; ?>                
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <?php
        echo $this->render('frontend/leftmenu-order');
        ?>     
    <div class="main">
        <h2> Chi tiết đơn hàng</h2>
        <h4>THÔNG TIN KHÁCH HÀNG</h4>
        <p>
            Họ tên : <?php echo $this->userInfo['fullname']; ?> <br>
            Địa chỉ : <?php echo $this->userInfo['address']; ?> <br>
            Số điện thoại : <?php echo $this->userInfo['phone']; ?><br>
            Email : <?php echo $this->userInfo['email']; ?>
        </p>
        <h4>TRẠNG THÁI ĐƠN HÀNG</h4>
        <p>
            Trạng thái : <?php if ($this->detailOrder['is_payment'] == 0) { ?>Chờ duyệt<?php }if ($this->detailOrder['is_payment'] == -1) { ?>Đã hủy<?php } if ($this->detailOrder['is_payment'] == 1) { ?>Đã duyệt<?php } ?><br>
            Mã đơn hàng : <?php echo $this->detailOrder['orde_code'] . $this->detailOrder['orde_id']; ?><br/>
            Ngày đặt hàng : <?php echo date('d/m/Y', $this->detailOrder['orde_created']); ?><br>
            Tổng tiền : <?php echo $this->detailOrder['orde_total_price'] ? number_format($this->detailOrder['orde_total_price'], 0, ",", ".") . ' VNĐ' : '0 VNĐ'; ?><br>
            Phương thức thanh toán :
            <?php
            foreach ($arrPaymentList as $key => $val) {
                if ($key == $this->detailOrder['orde_payment']) {
                    $Payment = $val;
                    break;
                }
            }
            echo $Payment ? $Payment : "Không xác định";
            ?>
        </p>
        <table class="table table-bordered width_100" border="0">
            <thead>
                <tr>
                    <th>Hình</th>
                    <th >Tên sản phẩm</th>
                    <th>Số lượng</th>
                    <th >Giá bán</th>
                    <th >Chiết khấu</th>
                    <th>Tổng tiền</th>
                </tr>
            </thead>
            <tbody>
            <input type="hidden" id="OrderID" value="<?php echo $this->detailOrder['orde_id']; ?>" />
            <?php
            if ($this->arrProductOrderList):
                foreach ($this->arrProductOrderList as $arrProductOrderList):
                    ?>
                    <tr>
                        <td class="text-center">
                            <?php
                            foreach ($this->arrDetailProduct as $val) {
                                if ($val['prod_id'] == $arrProductOrderList['prod_id']) {
                                    $prod_image = json_decode($val['prod_image'], TRUE);
                                    $prod_slug = $val['prod_slug'];
                                    break;
                                }
                            }
                            ?>
                            <a href="<?php echo $this->serverUrl() . $this->Url('product', array('productslug' => $prod_slug, 'productId' => $arrProductOrderList['prod_id'])); ?>">
                                <img src="<?php echo $prod_image['thumbImage']['170x170'] ?>" />
                            </a>
                        </td>
                        <td width="80"><a href="<?php echo $this->serverUrl() . $this->Url('product', array('productslug' => $prod_slug, 'productId' => $arrProductOrderList['prod_id'])); ?>"><?php echo $arrProductOrderList['prod_name']; ?></a></td>
                    <a href="../product/detail.phtml"></a>
                    <td class="text-center prodQuantity"><?php echo $arrProductOrderList['prod_quantity']; ?></td>
                    <td class="text-center prodPrice"><?php
                        if ($arrProductOrderList['prod_call_price'] != 1) {
                            echo number_format($arrProductOrderList['prod_price'], 0, ",", ".") . ' VNĐ';
                        } else {
                            ?>Giá liên hệ ...<br/>(Giá thực : <small class="text-muted " style="color:#F00"><?php echo number_format($arrProductOrderList['prod_price'], 0, ",", ".") . ' VNĐ'; ?></small>)<?php } ?></td>
                    <td class="text-center disCount"><?php echo $arrProductOrderList['discount']; ?>%</td>
                    <td class="text-center TotalPrice"><?php echo number_format($arrProductOrderList['total_price'], 0, ",", ".") . ' VNĐ'; ?></td> 
                    </tr>
                <?php endforeach; ?>
                <tr>
                    <td colspan="5" >
                        Tổng tiền
                    </td>
                    <td class="text-center">
                        <?php echo number_format($this->detailOrder['orde_total_price'], 0, ",", ".") . ' VNĐ'; ?>
                    </td>
                </tr>
            <?php else: ?>
                <tr><td colspan="6" class="text-center">Hiện tại không có sản phẩm.</td></tr>
            <?php endif; ?>
            </tbody>
        </table>
        <div>
            <?php echo $this->paging; ?>
        </div>
    </div>
          
    </div>
</div>