<div class="left">
    <div class="box">
        <div class="head box-head"> 
            Tài khoản của bạn
        </div>
        <div class="cont">
            <ul class="menu ">
                <li class="item active opened">
                    <a class="<?php echo ( $this->params['__CONTROLLER__'] == 'profile' && ( $this->params['action'] == 'index' || $this->params['action'] == 'edit' ) ) ? 'active' : null; ?>" href="<?php echo $this->serverUrl() . $this->Url('profile', array('controller' => 'profile', 'action' => 'index')) ?>">Thông tin cá nhân</a>
                </li>
            </ul>
        </div>
        <div class="cont">
            <ul class="menu ">
                <li class="item active opened">
                    <a class="<?php echo ( $this->params['__CONTROLLER__'] == 'order' && ( $this->params['action'] == 'index' || $this->params['action'] == 'edit' ) ) ? 'active' : null; ?>" href="<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'index')); ?>">Danh sách đơn hàng</a>
                </li>
            </ul>
        </div>
    </div>
</div>
