<!--search bar-->
<section id="searchBar">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <form method="GET" action="<?php echo $this->serverUrl() . $this->Url('search') ?>">
                    <div class="col-md-3">
                        <div class="label">
                            <select class="select" name="khu-vuc">
                                <option value="toan-tinh">Toàn tỉnh</option>
                                <?php foreach (unserialize(ARR_DISTRICT) as $value): ?>
                                    <option value="<?php echo $value['dist_slug'] ?>" <?php if ($this->params['khu-vuc'] == $value['dist_slug']) : ?>selected<?php endif; ?>><?php echo $value['dist_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="label">
                            <select class="select" name="danh-muc">
                                <option value="tat-ca-danh-muc">Tất cả danh mục</option>
                                <?php foreach (unserialize(ARR_CATEGORY_PARENT) as $value): ?>
                                    <option value="<?php echo $value['cate_slug'] ?>" <?php if ($this->params['danh-muc'] == $value['cate_slug']) : ?>selected<?php endif; ?>><?php echo $value['cate_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <input class="keyword" type="text" name="tu-khoa" placeholder="Nhập từ khóa..." value="<?php echo!empty($this->params['tu-khoa']) ? $this->params['tu-khoa'] : ''; ?>">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="search-btn">Tìm kiếm</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section> <!--end search bar-->
<div class="container">
    <section class="wrapper site-min-height">
        <div class="container">
            <div class="row">
                <section id="main-content">
                    <section class="wrapper">
                        <!-- page start-->
                        <section class="panel panel-success">
                            <header class="panel-heading">
                                <h4>KẾT QUẢ TÌM KIẾM  ||  Khu vực : <?php echo $this->params['khu-vuc']; ?> & Danh mục : <?php echo $this->params['danh-muc']; ?>   & Từ khóa : <?php echo $this->params['tu-khoa']; ?>  </h4>
                            </header>
                            <div class="panel-body">
                                <form class="form-horizontal search-result">
                                    <div class="form-group">
                                        <div class="col-lg-8 col-sm-8">
                                            <p class="help-block">Tìm thấy <b style="color: blue"><?php echo $this->intTotal ?></b> kết quả </p>
                                        </div>
                                    </div>
                                </form>
                                <table class="table table-striped table-condensed table-hover cf">
                                    <thead>
                                        <tr>
                                            <th class="text-center">Tiêu đề &amp; Nội dung</th>
                                            <th class="text-center">Danh mục</th>
                                            <th class="text-center">Khu vực</th>
                                            <th class="text-center">Nhu cầu</th>
                                            <th class="text-center">Xem</th>
                                            <th class="text-center">Ngày</th>
                                            <th class="text-center">Người đăng</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <?php
                                        if (!empty($this->arrContentList)):
                                            $arrCategorList = unserialize(ARR_CATEGORY);
                                            $arrDistrict = unserialize(ARR_DISTRICT);
                                            foreach ($this->arrContentList as $arrContent):
                                                ?>
                                                <tr>
                                                    <td>
                                                        <div class="hidden-phone">
                                                            <h4><a href="<?php echo $this->serverUrl() . $this->Url('view-content', array('contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id'])) ?>"><?php echo strlen($arrContent['cont_title']) > 100 ? substr($arrContent['cont_title'], 0, 100) . '...' : $arrContent['cont_title']; ?></a></h4>
                                                            <p style="white-space: pre-wrap"><?php echo strlen($arrContent['cont_detail_text']) > 400 ? substr(strip_tags($arrContent['cont_detail_text']), 0, 400) . '...' : $arrContent['cont_detail_text']; ?></p>
                                                        </div>
                                                    </td>
                                                    <td class="text-center"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('categorySlug' => $arrCategorList[$arrContent['cate_id']]['cate_slug'], 'categoryID' => $arrContent['cate_id'])) ?>" style="text-decoration: none; font-weight: bold"><?php echo $arrCategorList[$arrContent['cate_id']]['cate_name']; ?></a></td>
                                                    <td class="text-center"><?php echo (!empty($arrContent['dist_id'])) ? $arrDistrict[$arrContent['dist_id']]['cate_name'] : 'Toàn tỉnh'; ?></td>
                                                    <td class="text-center">Cần mua</td>
                                                    <td class="text-center"><?php echo $arrContent['cont_views']; ?></td>
                                                    <td class="text-center"><?php echo date('d.m.Y', $arrContent['created_date']); ?></td>
                                                    <td class="text-center">
                                                        <a class="btn btn-info btn-sm" href="javascript:;" >
                                                            <?php
                                                            if (!empty($arrContent['user_created'])) {
                                                                echo $this->arrUserList[$arrContent['user_created']]['user_fullname'];
                                                            } else {
                                                                echo $arrContent['user_info']['user_fullname'];
                                                            }
                                                            ?>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php
                                            endforeach;
                                        endif;
                                        ?>
                                    </tbody>
                                </table>

                                <div class="text-center">
                                    <?php echo $this->paging; ?>
                                </div>
                            </div>
                        </section>

                        <!-- page end-->
                    </section>
                </section>
                <!--main content end-->
            </div>
        </div>
    </section>
</div>
<!--main content start-->
