<!--search bar-->
<section id="searchBar">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <form method="GET" action="<?php echo $this->serverUrl() . $this->Url('search') ?>">
                    <div class="col-md-3">
                        <div class="label">
                            <select class="select" name="khu-vuc">
                                <option value="toan-tinh">Toàn tỉnh</option>
                                <?php foreach (unserialize(ARR_DISTRICT) as $value): ?>
                                    <option value="<?php echo $value['dist_slug'] ?>" <?php if ($this->params['khu-vuc'] == $value['dist_slug']) : ?>selected<?php endif; ?>><?php echo $value['dist_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="label">
                            <select class="select" name="danh-muc">
                                <option value="tat-ca-danh-muc">Tất cả danh mục</option>
                                <?php foreach (unserialize(ARR_CATEGORY_PARENT) as $value): ?>
                                    <option value="<?php echo $value['cate_slug'] ?>" <?php if ($this->params['danh-muc'] == $value['cate_slug']) : ?>selected<?php endif; ?>><?php echo $value['cate_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <input class="keyword" type="text" name="tu-khoa" placeholder="Nhập từ khóa..." value="<?php echo!empty($this->params['tu-khoa']) ? $this->params['tu-khoa'] : ''; ?>">
                    </div>
                    <div class="col-md-2">
                        <button type="submit" class="search-btn">Tìm kiếm</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section> <!--end search bar-->
<div class="container">
    <section class="wrapper site-min-height">
        <div class="container">
            <div class="row">
                <section id="main-content">
                    <section class="wrapper">
                        <!-- page start-->
                        <section class="panel panel-success">
                            <header class="panel-heading">
                                <h4>KẾT QUẢ TÌM KIẾM  :  Khu vực : <span style="color: blue"><?php echo $this->distName; ?></span> - Danh mục : <span style="color: blue"><?php echo $this->cateName; ?></span> <?php if (!empty($this->params['tu-khoa'])): ?> - Từ khóa : <span style="color: blue"><?php echo $this->params['tu-khoa']; ?> <?php endif; ?> </span></h4>
                            </header>
                            <div class="panel-body">
                                <form class="form-horizontal search-result">
                                    <div class="form-group">
                                        <div class="col-lg-8 col-sm-8">
                                            <p class="help-block">Tìm thấy <b style="color: blue"><?php echo $this->intTotal ?></b> kết quả </p>
                                        </div>
                                    </div>
                                </form>
                                <?php if (!empty($this->arrContentList)): ?>
                                    <table class="table table-striped table-condensed table-hover cf">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Tiêu đề</th>
                                                <th class="text-center" width="80px" style="color: #69A467">Danh mục</th>
                                                <th class="text-center" width="95px">Khu vực</th>
                                                <th class="text-center" width="70px">Nhu cầu</th>
                                                <th class="text-center">Xem</th>
                                                <th class="text-center">Ngày</th>
                                                <th class="text-center" width="120">Người đăng</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            $arrCategorList = unserialize(ARR_CATEGORY);
                                            $arrDistrict = unserialize(ARR_DISTRICT);
                                            foreach ($this->arrContentList as $arrContent):
                                                ?>
                                                <tr>
                                                    <td>
                                                        <div class="hidden-phone">
                                                            <h4><a href="<?php echo $this->serverUrl() . $this->Url('view-content', array('contentSlug' => $arrContent['cont_slug'], 'contentId' => $arrContent['cont_id'])) ?>"><?php echo strlen($arrContent['cont_title']) > 100 ? substr($arrContent['cont_title'], 0, 100) . '...' : $arrContent['cont_title']; ?></a></h4>
                                                            <p><?php echo strlen(html_entity_decode($arrContent['cont_detail_text'])) > 400 ? substr(strip_tags(html_entity_decode($arrContent['cont_detail_text'])), 0, 400) . '...' : html_entity_decode($arrContent['cont_detail_text']); ?></p>
                                                        </div>
                                                    </td>
                                                    <td class="text-center"><a href="<?php echo $this->serverUrl() . $this->Url('category', array('cateSlug' => $arrCategorList[$arrContent['cate_id']]['cate_slug'], 'cateId' => $arrContent['cate_id'])) ?>" style="text-decoration: none; font-weight: bold;color: #69A467"><?php echo $arrCategorList[$arrContent['cate_id']]['cate_name']; ?></a></td>
                                                    <td class="text-center"><?php echo (!empty($arrContent['dist_id'])) ? $arrDistrict[$arrContent['dist_id']]['dist_name'] : 'Toàn tỉnh'; ?></td>
                                                    <td class="text-center"><?php echo $this->arrPropertiesList[$arrContent['prop_id']]['prop_name']; ?></td>
                                                    <td class="text-center"><?php echo $arrContent['cont_views']; ?></td>
                                                    <td class="text-center"><?php echo date('d.m.y', $arrContent['created_date']); ?></td>
                                                    <td class="text-center">
                                                        <?php if (!empty($arrContent['user_created'])): ?>
                                                            <a style="text-decoration: none; font-size: 11px" href="<?php echo $this->serverUrl() . $this->Url('view-user-info', ['fullname' => \My\General::getSlug($this->arrUserList[$arrContent['user_created']]['user_fullname']), 'userId' => $this->arrUserList[$arrContent['user_created']]['user_id']]); ?>">
                                                                <b><?php echo $this->arrUserList[$arrContent['user_created']]['user_fullname']; ?></b>
                                                            </a>
                                                        <?php else : ?>
                                                            <a style="text-decoration: none; font-size: 11px" href="javascript:;" ><?php echo json_decode($arrContent['user_info'], true)['user_fullname']; ?></a>
                                                        <?php endif;
                                                        ?>
                                                        </a>
                                                    </td>
                                                </tr>
                                                <?php
                                            endforeach;
                                            ?>
                                        </tbody>
                                    </table>
                                <?php endif; ?>
                                <div class="text-center">
                                    <?php echo $this->paging; ?>
                                </div>
                            </div>
                        </section>
                        <!-- page end-->
                    </section>
                </section>
                <!--main content end-->
            </div>
        </div>
    </section>
</div>
<!--main content start-->
