<script type="text/javascript">
var checkoutURL = '<?php echo $this->serverUrl() . $this->Url('frontend-order', array('controller' => 'order', 'action' => 'update_cart_in_checkout')); ?>';
</script>
<?php
//die($this->Url('checkout_add_product',array('slug'=>'abc-a','id'=>3)));
$arrProductListCookie = $this->arrProductListCookie;
$listProductCart = $this->listProductCart;
$totalPriceOrder = 0;
?>

<div class="bar">
    <div class="bar-ps step-2">
        <div class="itm ps_1">
            <div class="pl">
                <div class="pr">
                    <div class="pc">THÔNG TIN<br>ĐƠN HÀNG</div>
                </div>
            </div>
        </div>
        <div class="itm ps_2 ">  <div class="pl">
                <div class="pr">
                    <div class="pc">HÌNH THỨC <br>THANH TOÁN</div>
                </div>
            </div>
        </div>
        <div class="itm ps_3">  <div class="pl">
                <div class="pr">
                    <div class="pc">ĐỊA CHỈ<br> GIAO HÀNG</div>
                </div>
            </div>
        </div>
        <div class="itm ps_4 ps_en">  <div class="pl">
                <div class="pr">
                    <div class="pc">HOÀN TẤT<br> ĐƠN HÀNG</div>
                </div>
            </div>
        </div>
        <div class="itm ps_5">&nbsp;</div>

        <div style="clear: both"></div>
    </div>
</div>
<div id="cont-checkout">
    <div class="main">
        <?php if($this->errors) :?>
        <div class="error-display text-center">
            <?php foreach($this->errors as $errors){
                echo '<span> - '.$errors.'</span><br/>';
            }?>
            <br/>
        </div>
        <?php endif;?>
        <form method="POST">
            <div class="page">
                <div class="card">
                    <table>
                        <tr>
                            <td class="ic">
                                <label for="optionsRadios1"><img  alt="" src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE ?>/images/cart.png"></label>
                            </td>
                            <td class="rd">
                                <input type="radio" value="1" id="optionsRadios1" name="payment" class="payment" <?php if($_SESSION["payment"]==1) echo 'checked';?>>
                            </td>
                            <td class="tx">
                                <label for="optionsRadios1"><strong>Chuyển khoản ngân hàng</strong>
                                <p>Chuyển khoản qua các ngân hàng Vietcombank, Viettinbank, Agribank, Ocenbank...</p></label>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="page">
                <div class="card">
                    <table>
                        <tr>
                            <td class="ic">
                                <label for="optionsRadios2"><img alt="" src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE ?>/images/pay_bkim.png"></label>
                            </td>
                            <td class="rd">
                                <input type="radio" value="2" id="optionsRadios2" name="payment" class="payment" <?php if($_SESSION["payment"]==2) echo 'checked';?>>
                            </td>
                            <td class="tx">
                                <label for="optionsRadios2"><strong>Thanh toán Bảo Kim</strong>
                                <p>Đảm bảo an toàn 100% thanh toán trực tuyến qua website</p></label>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="page">
                <div class="card">
                    <table>
                        <tr>
                            <td class="ic">
                                <label for="optionsRadios3"><img for="optionsRadios3" alt="" src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE ?>/images/pay_take.png"></label>
                            </td>
                            <td class="rd">
                                <input type="radio" value="3" id="optionsRadios3" name="payment" class="payment" <?php if($_SESSION["payment"]==3) echo 'checked';?>>
                            </td>
                            <td class="tx">
                                <label for="optionsRadios3"><strong>Thanh toán khi nhận hàng</strong>
                                <p>Nhân viên giao hàng của chúng tôi sẽ thu tiền tại nhà của bạn khi giao hàng</p></label>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>

            <div class="page-1">
                <div class="button">
                    <a id="modal_trigger_n" class="checkOut"><button class=" btn-next" type="submit">Tiếp tục đặt hàng &gt;&gt;</button></a>
                </div>
                <div class="card">
                    <div class="pay-logo">
                        <div class="proship">
                            <p><strong>Dịch vụ vận chuyển nội thành nhanh nhất</strong></p>
                            <p class="img"><a target="_bank" title="Proship" href="http://proship.vn"><img alt="proship" src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE ?>/images/prohip.jpg"></a></p>
                        </div>
                        <div class="baokim">
                            <p><strong>Thanh toán đảm bảo</strong></p>
                            <p><a target="_bank" title="baokim" href="http://baokim.vn"><img alt="baokim" src="<?php echo STATIC_URL . '/f/' . FRONTEND_TEMPLATE ?>/images/baokim.jpg"></a></p>
                        </div>

                    </div>
                </div>
            </div>

        </form>
    </div>
    <div class="right">
        <div class="info">
            <div class="head"><h2>Bạn có <?php echo count($arrProductListCookie); ?> sản phẩm trong giỏ hàng</h2></div>
            <div>
                <table>
                    <tbody><tr class="hd">
                            <td class="sp">Sản phẩm</th>
                            <td class="name">&nbsp;</th>
                            <td class="number">Số lượng</th>
                            <td class="price">Giá</th>
                            <td class="price">Thành tiền</th>
                        </tr>
                        <?php
                        foreach ($listProductCart as $keyListProduct => $valueListProduct) {
                           // p($valueListProduct['prod_is_promotion']);die;
                            if ($valueListProduct['prod_is_promotion'] == 1) {
                                $totalPriceOrder = $totalPriceOrder + ($valueListProduct['prod_promotion_price'] * $arrProductListCookie[$valueListProduct['prod_id']]['quantity']);
                            } else {
                                $totalPriceOrder = $totalPriceOrder + ($valueListProduct['prod_price'] * $arrProductListCookie[$valueListProduct['prod_id']]['quantity']);
                            }
                            ?>
                            <tr class="detaiProduct">
                                <td><a href="<?php echo $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $valueListProduct["prod_slug"], 'productId' => $valueListProduct['prod_id'])); ?>"><img alt="" width="60" src="<?php echo json_decode($valueListProduct['prod_image'], true)['thumbImage']['224x224']; ?>"></a></td>
                                <td><strong><?php echo $valueListProduct['prod_name'] ?></strong></td>
                                <td>
                                    <select class="form-control quantity" id="29" rel="<?php echo $valueListProduct['prod_id']?>">
                                        <?php for ($i = 1; $i <= 20; $i++) { ?>
                                            <option value="<?php echo $i ?>" <?php
                                            if ($arrProductListCookie[$valueListProduct['prod_id']]['quantity'] == $i) {
                                                echo 'selected';
                                            }
                                            ?>><?php echo $i; ?></option>
                                                <?php } ?>
                                    </select>
                                </td>
                                <td class="price">
                                    <?php echo ($valueListProduct['prod_is_promotion'] == 1) ? number_format($valueListProduct['prod_promotion_price'], 0, ",", ".") : number_format($valueListProduct['prod_price'], 0, ",", "."); ?>VNĐ<br>
                                    <?php if ($valueListProduct['prod_is_promotion'] == 1) { ?><p style="text-decoration:line-through;"><?php echo number_format($valueListProduct['prod_price'], 0, ",", ".") ?> VNĐ</p><?php } ?>
                                </td>
                                <td class ='total'>
                                    <?php echo ($valueListProduct['prod_is_promotion'] == 1) ? number_format($valueListProduct['prod_promotion_price']*$arrProductListCookie[$valueListProduct['prod_id']]['quantity']) : number_format($valueListProduct['prod_price']*$arrProductListCookie[$valueListProduct['prod_id']]['quantity']); ?> VNĐ<br>
                                </td>
                            </tr>
                        <?php } ?>
                        <tr class="sum">
                            <td colspan="4">Tổng cộng</td>
                            <td class = "totalPriceOrder"> <?php echo number_format($totalPriceOrder, 0, ",", ".") ?> VNĐ </td>
                        </tr>
                        <tr class="sum">
                            <td colspan="4">Phí thực hiện đơn hàng</td>
                            <td> Miễn phí </td>
                        </tr>
                        <tr class="sum">
                            <td colspan="4">Thành tiền (Đã bao gồm VAT)</td>
                            <td class = "totalPriceOrder"><?php echo number_format($totalPriceOrder, 0, ",", ".") ?> VNĐ </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div style="clear: both"></div>
</div>
<script>
Checkout.index();
</script>