<section id="categories">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="main-heading text-center">
                    <h2>CATEGORIES</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-briefcase fa-2x"></i>
                    </div>
                    <h4><a href="#">JOBS</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-home fa-2x"></i>
                    </div>
                    <h4><a href="#">REAL ESTATE</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-truck fa-2x"></i>
                    </div>
                    <h4><a href="#">VEHICLES</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-lightbulb-o fa-2x"></i>
                    </div>
                    <h4><a href="#">ELECTRONICS</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-github fa-2x"></i>
                    </div>
                    <h4><a href="#">PETS</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-wrench fa-2x"></i>
                    </div>
                    <h4><a href="#">SERVICES</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-female fa-2x"></i>
                    </div>
                    <h4><a href="#">FASHION</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
            <div class="col-md-3 col-sm-6">
                <div class="category">
                    <div class="category-icon">
                        <i class="fa fa-heart fa-2x"></i>
                    </div>
                    <h4><a href="#">MATRIMONIALS</a></h4>
                    <p><a href="#">Design & Development Jobs  ( 20 )</a></p>
                    <p><a href="#"> Marketing Jobs  ( 09 )</a></p>
                    <p><a href="#"> Accounts & Finance Jobs  ( 15 )</a></p>
                    <p><a href="#"> Cleaning Jobs  ( 0 )</a></p>
                    <p><a href="#"> Others  ( 160 )</a></p>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="advertise">
                    <a href="#"><img src="images/images/ad_03.png" alt="ad"> </a>
                </div>
            </div>
        </div>
    </div>
</section>