<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Tin nhắn từ - <?php echo My\General::SITE_AUTH; ?>">
        <meta name="author" content="<?php echo My\General::SITE_AUTH; ?>">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> 
        <title>Nhadat.net</title>
    </head>
    <body>
        <div style="width: 635px; margin: 50px auto; position: relative; overflow: hidden;font-family: arial;">
            <div style="overflow: hidden; padding: 10px 0; margin-bottom: 50px">
                <div style="float: left !important;"><a href="<?php echo BASE_URL; ?>" style="color: #22a0e2;"><img src="<?php echo STATIC_URL . '/f/v1/images/logoct.png'; ?>" alt="<?php echo My\General::SITE_AUTH; ?>"></a></div>
            </div>
            <div style="border-bottom: 1px solid #e6e6e6;">
                <h4 style="color: #454545; font-weight: bold; font-size: 18px;">Xin chào <?php echo $this->arrUserInfo['user_fullname']; ?> !</h4>
                <p style="color: #454545; font-size: 18px;">
                    Bạn nhận được 1 tin nhắn mới từ người dùng có tên là : <?php echo $this->from_user_name; ?>
                </p>
                <p style="color: #454545; font-size: 14px; text-align:center">
                    Vui lòng Đăng nhập vào hệ thống của chúng tôi và vào trang quản lý cá nhân để xem nội dung tin nhắn!
                </p>
            </div>
            <?php echo $this->render('frontend/footer-email'); ?>
        </div>
    </body>
</html>