<?php
$name = !empty($this->arrUser) ? $this->arrUser['user_fullname'] : $this->arrMessages['user_info']['user_fullname'];
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="Tin nhắn từ - <?php echo My\General::SITE_AUTH; ?>">
        <meta name="author" content="<?php echo My\General::SITE_AUTH; ?>">
        <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'> 
        <title>Nhadat.net</title>
    </head>
    <body>
        <div style="width: 635px; margin: 50px auto; position: relative; overflow: hidden;font-family: arial;">
            <div style="overflow: hidden; padding: 10px 0; margin-bottom: 50px">
                <div style="float: left !important;"><a href="<?php echo BASE_URL; ?>" style="color: #22a0e2;"><img src="<?php echo STATIC_URL . '/f/v1/images/logoct.png'; ?>" alt="<?php echo My\General::SITE_AUTH; ?>"></a></div>
            </div>
            <div style="border-bottom: 1px solid #e6e6e6;">
                <h4 style="color: #454545; font-weight: bold; font-size: 18px;">Xin chào <?php echo $name; ?> !</h4>
                <p style="color: #454545; font-size: 18px;">
                    Bạn nhận được 1 tin nhắn mới trong tin : 
                </p>
                <div style="color: #454545; font-size: 18px; margin-bottom: 30px; padding: 30px 0 20px;">
                    <center><div style="color: #e65711; border: none; padding: 10px 0; font-size: 30px; border-radius: 4px; cursor: pointer"><a style="text-decoration:none;" href="<?php echo $this->serverUrl() . $this->Url('view-content', array('contentSlug' => $this->arrContent['cont_slug'], 'contentId' => $this->arrContent['cont_id'])); ?>">&#xbb; <?php echo $this->arrContent['cont_title']; ?> &#xab;</a></div></center>
                </div>
                <?php if (empty($this->arrUser)) : ?>
                    <p style="color: #454545; font-size: 14px; text-align:center">
                        <?php echo $this->arrMessages['mess_content']; ?>
                    </p>
                    <div style="color: #454545; font-size: 18px; margin-bottom: 30px; padding: 15px 0 30px;">
                        <center><div style="color: #333; background: #eee; border: none; padding: 10px 10px; font-size: 18px; border-radius: 4px; width: 150px; cursor: pointer"><?php echo $this->arrMessages['mess_content']; ?></div></center>
                    </div>
                <?php else: ?>
                    <p style="color: #454545; font-size: 14px; text-align:center">
                        Vui lòng Đăng nhập vào hệ thống của chúng tôi và vào trang quản lý cá nhân để xem nội dung tin nhắn!
                    </p>
                <?php endif; ?>
            </div>
            <?php echo $this->render('frontend/footer-email'); ?>
        </div>
    </body>
</html>