<div style="margin: 40px 0 40px; text-align: center;">
    <p style="color: #454545; font-size: 15px; text-align: center; margin-top: 8px;">
        <a href="<?php echo BASE_URL; ?>" style="color: #22a0e2; text-decoration: none;"><?php echo My\General::SITE_DOMAIN?></a> - <?php echo My\General::SITE_SLOGAN?> 
    </p>
    <div style="margin:30px 0; font-size: 15px;">Mọi chi tiết liên hệ</div>
    <p style="color: #5b5b5b; font-size: 15px; line-height: 23px;">
        Công ty <?php echo My\General::SITE_AUTH;?><br />
        Nguyễn Huệ, TP. Quy Nhơn, Bình Định <br />
        <span style=" color: #e65711">Hotline <?php echo My\General::SITE_HOTLINE?></span>
    </p>
</div>