<?php
$paramsRouter = $this->getHelperPluginManager()->getServiceLocator()->get('Application')->getMvcEvent()->getRouteMatch()->getParams();
$controller = $paramsRouter['__CONTROLLER__'];
?>
<section id="header">
    <header>
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 responsive-width-top">
                        <div class="social">
                            <div class="social-icon">
                                <a href="https://www.facebook.com/quynhonchotot"><i class="fa fa-facebook"></i></a>
                                <a href="https://twitter.com/chototquynhon"><i class="fa fa-twitter"></i></a>
                                <a href="https://plus.google.com/u/0/110877749133479386855/posts"><i class="fa fa-google-plus"></i></a>
                                <a href="#"><i class="fa fa-linkedin"></i></a>
                                <a href="#"><i class="fa fa-dribbble"></i></a>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-6 responsive-width-top">
                        <div class="links text-right">
                            <a href="<?php echo $this->serverUrl() . $this->Url('addcontent', array('controller' => 'content', 'action' => 'add')) ?>"> <i class="fa fa-pencil-square-o"></i> Đăng rao vặt</a>
                            <?php if (CUSTOMER_ID == 0): ?>
                                <a id="loginRegister" href="javascript:;"><i class="fa fa-user-plus"></i> Đăng ký</a>
                                <a id="loginButton" href="javascript:;"><i class="fa fa-sign-in"></i> Login</a>
                            <?php else: ?>
                                <a href="<?php echo $this->serverUrl() . $this->Url('user-profile') ?>"><i class="fa fa-user"></i> Tài khoản</a>
                                <a href="<?php echo $this->serverUrl() . $this->Url('auth', array('controller' => 'auth', 'action' => 'logout')) ?>"><i class="fa fa-sign-out"></i> Signout</a>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
            </div>
        </div><!--end top bar-->

        <!--start menu-bar-->
        <div class="menu-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-4">
                        <div class="logo">
                            <a href="<?php echo $this->serverUrl(); ?>"><img src="<?php echo STATIC_URL; ?>/f/v1/images/logoct.png" alt="classify"></a>
                        </div>
                    </div>
                    <div class="col-sm-8">
                        <nav role="navigation" class="navbar navbar-default">
                            <!-- Brand and toggle get grouped for better mobile display -->
                            <div class="navbar-header">
                                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                                    <span class="sr-only">Toggle navigation</span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>
                            <!-- Collection of nav links and other content for toggling -->
                            <div id="navbarCollapse" class="collapse navbar-collapse">
                                <ul class="nav navbar-nav navbar-right">
                                    <li class="active dropdown">
                                        <a class="dropdown-toggle" href="<?php echo $this->serverUrl(); ?>">Trang chủ</a>
                                    </li>
                                    <li><a href="<?php echo $this->serverUrl() . $this->Url('general', array('controller' => 'general', 'action' => 'index', 'title' => $arrGeneral[13]['gene_slug'], 'id' => 13)) ?>">Giới thiệu</a></li>
                                    <li class="dropdown">
                                        <a href="javascript:;">Danh mục</a>
                                        <ul class="dropdown-menu sub-menu">
                                            <?php foreach (unserialize(ARR_CATEGORY_PARENT) as $value): ?>
                                                <li><a href="<?php echo $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'cateSlug' => $value["cate_slug"], 'cateId' => $value["cate_id"])) ?>"><?php echo $value['cate_name'] ?></a></li>
                                            <?php endforeach; ?>
                                        </ul>
                                    </li>

                                    <li class="dropdown">
                                        <a class="dropdown-toggle" href="javascript:;">Thông tin khác</a>
                                        <ul class="dropdown-menu sub-menu">
                                            <li><a href="detail-page.html">Hướng dẫn</a></li>
                                            <li><a href="faq.html">FAQ</a></li>
                                            <li><a href="notification.html">Thông báo</a></li>
                                            <li><a href="detail-page.html">Chi tiêt trang</a></li>
                                        </ul>
                                    </li>
                                    <li><a href="<?php echo $this->serverUrl() . $this->Url('add-contact') ?>">Liên hệ</a></li>
                                </ul>
                            </div>
                        </nav><!--end nav-->
                    </div>
                </div>
            </div>
        </div><!--end menu-bar-->
    </header>
</section>

<?php if ($controller !== 'search'): ?>
    <!--search bar-->
    <section id="searchBar">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-12">
                    <form method="GET" action="<?php echo $this->serverUrl() . $this->Url('search') ?>">
                        <div class="col-md-3">
                            <div class="label">
                                <select class="select" name="khu-vuc">
                                    <option value="toan-tinh">Chọn khu vực</option>
                                    <option value="toan-tinh">Toàn tỉnh</option>
                                    <?php foreach (unserialize(ARR_DISTRICT) as $value): ?>
                                        <option value="<?php echo $value['dist_id'] ?>"><?php echo $value['dist_name']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-3">
                            <div class="label">
                                <select class="select" name="danh-muc">
                                    <option value="tat-ca-danh-muc">Chọn danh mục</option>
                                    <option value="tat-ca-danh-muc">Tất cả danh mục</option>
                                    <?php foreach (unserialize(ARR_CATEGORY_PARENT) as $value): ?>
                                        <option value="<?php echo $value['cate_id'] ?>"><?php echo $value['cate_name']; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <input class="keyword" type="text" name="tu-khoa" placeholder="Nhập từ khóa...">
                        </div>
                        <div class="col-md-2">
                            <button type="submit" class="search-btn">Tìm kiếm</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section> <!--end search bar-->
<?php endif; ?>