<div class="menu-bar">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="logo">
                    <a href="#"><img src="images/logo.png" alt="classify"></a>
                </div>
            </div>
            <div class="col-sm-8">
                <nav role="navigation" class="navbar navbar-default">
                    <!-- Brand and toggle get grouped for better mobile display -->
                    <div class="navbar-header">
                        <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <!-- Collection of nav links and other content for toggling -->
                    <div id="navbarCollapse" class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active dropdown">
                                <a class="dropdown-toggle" href="index-2.html">Home</a>
                                <ul class="dropdown-menu sub-menu">
                                    <li><a href="home-page-with-map.html">Home Page v1</a></li>
                                    <li><a href="home-page-without-slider.html">Home Page v2</a></li>
                                </ul>
                            </li>
                            <li><a href="fullwidth-page-sidebar.html">About</a></li>
                            <li><a href="pricing-plan.html">Pricing Plan</a></li>
                            <li><a href="subcategory.html">Categories</a></li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="#">Features</a>
                                <ul class="dropdown-menu sub-menu">
                                    <li><a href="faq.html">FAQ</a></li>
                                    <li><a href="notification.html">Notification</a></li>
                                    <li><a href="fullwidth-page.html">Full width Page</a></li>
                                </ul>
                            </li>
                            <li class="dropdown">
                                <a class="dropdown-toggle" href="#">Other</a>
                                <ul class="dropdown-menu sub-menu">
                                    <li><a href="detail-page.html">Detail Page</a></li>
                                    <li><a href="edit-ad.html">Edit Ad</a></li>
                                    <li><a href="edit-profile.html">Edit Profile</a></li>
                                    <li><a href="profile.html">Profile</a></li>
                                    <li><a href="profile-second.html">Profile v2</a></li>
                                    <li><a href="reset.html">Rset Password</a></li>
                                </ul>
                            </li>
                            <li><a href="contact.html">Contact</a></li>
                        </ul>
                    </div>

                </nav><!--end nav-->
            </div>
        </div>
    </div>
</div>