<section id="premium">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="main-heading text-center">
                    <h2>PREMIUM ADVERTISEMENT</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="owl-carousel">
                <div class="item">
                    <a href="#"><img src="images/images/carou1_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Old Car</a></div>
                    <a href="#" class="item-hover"><span>$199</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou2_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Expensive Car</a></div>
                    <a href="#" class="item-hover"><span>$299</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou3_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Antique things for sale</a></div>
                    <a href="#" class="item-hover"><span>$499</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou4_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Creative Tattos</a></div>
                    <a href="#" class="item-hover"><span>$99</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou1_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Old Car</a></div>
                    <a href="#" class="item-hover"><p>$199</p></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou1_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Old Car</a></div>
                    <a href="#" class="item-hover"><span>$199</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou2_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Expensive Car</a></div>
                    <a href="#" class="item-hover"><span>$299</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou3_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Antique things for sale</a></div>
                    <a href="#" class="item-hover"><span>$499</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou4_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Creative Tattos</a></div>
                    <a href="#" class="item-hover"><span>$99</span></a>
                </div>
                <div class="item">
                    <a href="#"><img src="images/images/carou1_03.png" alt="carousel"></a>
                    <div class="item-title"><a href="#">Old Car</a></div>
                    <a href="#" class="item-hover"><span>$199</span></a>
                </div>
            </div><!--end carousel-->
        </div>
    </div>
</section>