<?php
$arrCategory = $this->arrCategory;
?>
<section class="wrapper site-min-height">
    <?php if ($this->errors): ?>
        <div class="alert alert-block alert-danger fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
            <?php foreach ($this->errors as $error): ?>
                <p> - <?php echo $error; ?></p>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>

    <?php
    $successMessage = array_merge($this->flashMessenger()->setNamespace('success-edit-category')->getMessages());
    if ($successMessage):
        ?>
        <div class="alert alert-success alert-block fade in">
            <button class="close close-sm" type="button" data-dismiss="alert">
                <i class="fa fa-times"></i>
            </button>
            <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
            <p>- <?php echo current($successMessage); ?></p>
        </div>
    <?php endif; ?>
    <section class="panel panel-primary">
        <header class="panel-heading">CHỈNH SỬA DANH MỤC MỚI</header>
        <div class="panel-body">

            <form id="frm" class="form-horizontal tasi-form"  method="POST">

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_name">Tên Danh mục <span style="color:red">*</span></label>
                    <div class="col-lg-5">
                        <input id="cate_name" name="cate_name" class="form-control" type="text" placeholder="Vui lòng nhập tên danh mục" value="<?php echo $this->params['cate_name'] ? $this->params['cate_name'] : $arrCategory['cate_name']; ?>">
                    </div>
                </div>
                <?php if (!empty($arrParentList)): ?>
                    <div class="form-group">
                        <label  class="col-lg-2 control-label">Chọn Danh mục cha</label>
                        <div class="col-lg-5">
                            <select name="parent_id" class="form-control parent_id">
                                <option value="0">Vui lòng chọn danh mục cha</option>
                                <?php
                                foreach ($arrParentList as $arrParent):
                                    ?>
                                    <option value="<?php echo $arrParent['cate_id']; ?>" <?php echo ($this->params['parent_id'] == $arrParent['cate_id']) ? 'selected' : ($arrCategory['parent_id'] == $arrParent['cate_id'] ? 'selected' : null); ?>><?php echo $arrParent['cate_name']; ?></option>
                                    <?php
                                endforeach;
                                ?>
                            </select>
                        </div>
                    </div>
                <?php endif; ?>
                <div class="form-group select-icon">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_icon">Icon cho Danh mục<span style="color:red">*</span></label>
                    <div class="col-lg-5">
                        <input id="cate_name" name="cate_icon" class="form-control" type="text" placeholder="Icon cho danh mục" value="<?php echo $this->params['cate_icon'] ? $this->params['cate_icon'] : $arrCategory['cate_icon']; ?>">
                    </div>

                    <div class="col-lg-5">
                        <a href="<?php echo $this->serverUrl() . $this->Url('backend', array('controller' => 'category', 'action' => 'change-icon')); ?>" target="_blank"> <b> <i class=" icon-hand-right"></i> Kích vào đây để Chọn Icon <i class="icon-hand-left"></i></b></a>
                    </div>
                </div>

                <div class="form-group select-prop">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_icon">Chọn nhóm nhu cầu cho danh mục</label>
                    <div class="col-lg-5">
                        <select name="prop_id" class="form-control prop_id">
                            <option value="0" <?php if (empty($this->params['prop_id'])): ?> selected="selected"<?php endif; ?>>Vui lòng chọn nhu cầu</option>
                            <?php
                            if (!empty($arrPropertiesList)):
                                foreach ($arrPropertiesList as $arrProperties):
                                    ?>
                                    <option value="<?php echo $arrProperties['prop_id']; ?>" <?php echo (!empty($this->params['prop_id']) && $this->params['prop_id'] == $arrProperties['prop_id']) ? 'selected' : ($arrCategory['prop_id'] == $arrProperties['prop_id'] ? 'selected' : ''); ?>><?php echo $arrProperties['prop_name']; ?></option>
                                    <?php
                                endforeach;
                            endif;
                            ?>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_sort">Sắp xếp</label>
                    <div class="col-lg-5">
                        <input id="cate_sort" name="cate_sort" class="form-control" type="text" placeholder="Vui lòng nhập độ ưu tiên" value="<?php echo $this->params['cate_sort'] ? $this->params['cate_sort'] : $arrCategory['cate_sort']; ?>">
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_meta_title">SEO Meta title <span style="color:red">*</span></label>
                    <div class="col-lg-10">
                        <input id="cate_meta_title" name="cate_meta_title" class="form-control" type="text" placeholder="Nhập meta title cho Danh mục" value="<?php echo $this->params['cate_meta_title'] ? $this->params['cate_meta_title'] : $arrCategory['cate_meta_title']; ?>" >
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_meta_description">SEO Meta Description <span style="color:red">*</span></label>
                    <div class="col-lg-10">
                        <textarea id="cate_meta_description" rows="6" name="cate_meta_description" class="form-control editor" placeholder="Nhập meta description cho Danh mục" ><?php echo ($this->params['cate_meta_description']) ? $this->params['cate_meta_description'] : $arrCategory['cate_meta_description']; ?></textarea>
                    </div>
                </div>

                <div class="form-group">
                    <label class="col-lg-2 col-sm-2 control-label" for="cate_meta_keyword">SEO Meta Keyword <span style="color:red">*</span></label>
                    <div class="col-lg-10">
                        <input id="cate_meta_keyword" name="cate_meta_keyword" class="form-control" type="text" placeholder="Nhập meta keyword cho Danh mục" value="<?php echo $this->params['cate_meta_keyword'] ? $this->params['cate_meta_keyword'] : $arrCategory['cate_meta_keyword']; ?>" >
                    </div>
                </div>

                <div class="form-group">
                    <label  class="col-lg-2 control-label">Trạng thái<span style="color:red">*</span></label>
                    <div class="col-lg-4">
                        <select name="cate_status" class="form-control">
                            <option value="1" <?php echo ($arrCategory['cate_status'] == 1) ? 'selected' : ''; ?>>Hiển thị</option>
                            <option value="0" <?php echo ($arrCategory['cate_status'] == 0) ? 'selected' : ''; ?>>Ẩn</option>
                        </select>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-lg-offset-2 col-lg-10">
                        <button type="submit" id="done" class="btn btn-success bt-save" name="save"><i class="icon-save"></i> Lưu</button>  
                    </div>
                </div>

            </form>
        </div>
    </section>
    <input type="hidden" class="parent" value="<?php echo $arrCategory['parent_id']; ?>">
</section>
<script type="text/javascript">
    Category.edit();
</script>
