<section id="detail">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="page-content">
                    <h4 class="inner-heading"><?php echo $this->arrGeneralDetail['gene_title'] ?></h4>
                    <?php echo $this->arrGeneralDetail['gene_content'] ?>
                </div>
            </div>
        </div>
    </div>
</section>