<?php

use My\General;

$linkIndex = $this->serverUrl() . $this->Url('frontend', array('controller' => 'index', 'action' => 'index'));
$brand = implode('--', $this->params['brandSlug']);
$arrProductList = $this->arrProductList;
$arrCategoryParentList = $this->arrCategoryParentList;
$getDetailCategory = $this->getDetailCategory;
$arrBrandList = $this->arrBrandList;
$linkCateBrand = $this->LinkCateBrand;
$BrandDetailListID = array();
foreach ($this->BrandDetailList as $key => $value) {
    $BrandDetailListID[] = $value['cate_id'];
}
$arrCategoryList = unserialize(ARR_CATEGORY_LIST);
//p($arrCategoryList);
//die;
?>
<div id="content">
    <div class="block-head">
        <div class="menu">
            <div class="m-level">
                <div class="title">
                    <span class="icon i-list"></span> <div class="text">TẤT CẢ DANH MỤC</div>
                </div>
                <div class="list">
                </div>
            </div>
        </div>
        <div class="breadcrumb"   itemscope itemtype="http://data-vocabulary.org/Breadcrumb">
            <div class="item">
                <div class="ar-right">
                    <div class="cont">
                        <a style="text-decoration: none;cursor:default" itemprop="url"><span itemprop="title">Thương hiệu</span></a>
                    </div>
                </div>
            </div>
            <div class="item-end">
                <div class="ar-right">
                    <div class="cont">
                        <a style="text-decoration: none;cursor:default" itemprop="url"><span itemprop="title"><?php echo $this->params['brand_name'][0]; ?></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div style="clear: both;"></div>
    </div>
    <div class="block-content">
        <div class="left">
            <?php
            if ($this->arrCateGradeList[0]) {
                $arrCategoryList = $this->arrCateGradeList;
                ?>
                <div class="box">
                    <div class="head box-head">
                        <?php echo $arrCategoryList[0]['cate_name'] ?>
                    </div>
                    <div class="cont">
                        <ul class="menu ">
                            <?php
                            $arrCate = array();
                            foreach ($arrCategoryList as $key => $value) {
                                $arrCate[$key] = $value;
                                $arrParams = array('controller' => 'brand', 'action' => 'index', 'categorySlug' => $value["cate_slug"], 'categoryID' => $value["cate_id"], 'brandSlug' => $brand, 'price' => $this->params['price']);
                                $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                                $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                                $cateLink = $this->serverUrl() . $this->Url('brand', $arrParams);
                                $arrCate[$key]["cate_link"] = $cateLink;
                            }
                            $arrInput = My\General::arrCateInput($arrCate, $arrCate[0]['cate_id']);
                            echo My\General::arrCateOutput($arrInput, 1, $this->params['categoryID'])["result"];
                            ?>
                        </ul>
                    </div>
                </div>
                <?php
            } else {
                ?>
                <div class="box">
                    <div class="head box-head">
                        Tìm kiếm theo danh mục
                    </div>
                    <div class="cont">
                        <ul class="menu ">
                            <?php
                            foreach ($arrCategoryParentList as $value) {
                                $arrParams = array('controller' => 'brand', 'action' => 'index', 'categorySlug' => $value["cate_slug"], 'categoryID' => $value["cate_id"], 'brandSlug' => $brand, 'price' => $this->params['price']);
                                $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                                $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                                $cateLink = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <li class="item unopened"><a href="<?php echo $cateLink; ?>"><?php echo $value['cate_name']; ?></a></li>
                            <?php }
                            ?>
                        </ul>
                    </div>
                </div>
                <?php
            }
            ?>
            <div class="box">
                <div class="head">Giá sản phẩm</div>
                <div class="cont">
                    <div class="sider-select">
                        <input class="range-slider" type="hidden" value="10000,10000000"/>
                    </div>
                    <div class="texbox">
                        <?php
                        $arrParams = array('controller' => 'brand', 'action' => 'index', 'brandSlug' => $brand, 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug']);
                        $linkPrice = $this->serverUrl() . $this->Url('brand', $arrParams);
                        ?>
                        <input class="text price-from" value="<?php echo $this->params['price_start'] ? $this->params['price_start'] : 1000 ?>" name="start"/> VNĐ ->  
                        <input class="text  price-to" value="<?php echo $this->params['price_end'] ? $this->params['price_end'] : 10000000 ?>" name="end"/> VNĐ 
                        <form method="GET" action="<?php echo $linkPrice; ?>">
                            <?php echo $this->params['s'] ? '<input type="hidden" name="s" value="' . $this->params['s'] . '" />' : NULL; ?>
                            <input type="hidden" name="price" class="price_search" value="" />
                            <?php echo $this->params['sort'] ? '<input type="hidden" name="sort" value="' . $this->params['sort'] . '" />' : NULL; ?>
                            <button class="search" type="submit">Tìm</button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="line"></div>
            <div class="box">
                <div class="head">Thương hiệu</div>
                <div class="cont">
                    <div class="selected">
                        <?php
                        $arrParams = array('controller' => 'brand', 'action' => 'index', 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                        $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                        $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                        foreach ($BrandDetailList as $key => $value):
                            if (!in_array($value['cate_slug'], $this->params['brand'])) {
                                $arrParams['brandSlug'] = $brand . '--' . $val['cate_slug'];
                            } else {
                                $arrParams['brandSlug'] = $brand;
                            }
                            ?>
                            <div class="item">
                                <input type="checkbox" class="css-checkbox search-brand" id="<?php echo $value['cate_name'] ?>" name="brand[]" value="<?php echo $value['cate_slug'] ?>" checked="checked" >
                                <?php
                                foreach ($this->params['brand_name'] as $v) {
                                    if ($v == $value['cate_name']) {
                                        $arrParams['brandSlug'] = $arrParams['brandSlug'] . '--'; //ex : a--b--c--
                                        $arrParams['brandSlug'] = trim(str_replace($value['cate_slug'] . '--', NULL, $arrParams['brandSlug']), '--');
                                        break;
                                    }
                                }
                                $linkBrand = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <label for="<?php echo $value['cate_name'] ?>" class="css-label lite-green-check"><?php echo $value['cate_name']; ?></label>
                                <input type="hidden" value="<?php echo $linkBrand; ?>" />
                            </div>
                        <?php endforeach; ?>
                        <?php
                        foreach ($arrBrandList as $val) {
                            if (!in_array($val['cate_id'], $BrandDetailListID)) {
                                if (!in_array($val['cate_slug'], $this->params['brand'])) {
                                    $arrParams['brandSlug'] = $brand . '--' . $val['cate_slug'];
                                } else {
                                    $arrParams['brandSlug'] = $brand;
                                }
                                ?>
                                <div class="item">
                                    <input type="checkbox" class="css-checkbox search-brand" id="<?php echo $val['cate_name'] ?>" name="brand[]" value="<?php echo $val['cate_slug'] ?>" <?php
                                    foreach ($this->params['brand_name'] as $value) {
                                        if ($value == $val['cate_name']) {
                                            $arrParams['brandSlug'] = $arrParams['brandSlug'] . '--'; //ex : a--b--c--
                                            $arrParams['brandSlug'] = trim(str_replace($val['cate_slug'] . '--', NULL, $arrParams['brandSlug']), '--');
                                            break;
                                        }
                                    }
                                    $linkBrand = $this->serverUrl() . $this->Url('brand', $arrParams);
                                    ?>>
                                    <label for="<?php echo $val['cate_name'] ?>" class="css-label lite-green-check"><?php echo $val['cate_name']; ?></label>
                                    <input type="hidden" value="<?php echo $linkBrand; ?>" />
                                </div>
                                <?php
                            }
                        }
                        ?>
                    </div>
                </div>
            </div>
            <div class="line"></div>
        </div>

        <div class="main">
            <div class="banner">
                <!--class="lazy" data-original=" src="images/banner.png"/>-->
            </div>
            <div class="list-prod">
                <div class="title">
                    <h1>
                        <?php
                        $brandName = $this->params['brand_name'][0];
                        if (!empty($linkCateBrand)):
                            empty($linkCateBrand['link_meta_title']) ? $brandName = $cateDetailList[0]["cate_name"] . " " . $brandDetailList[0]["cate_name"] : $brandName = $linkCateBrand['link_meta_title'];
                        endif;
                        echo $brandName;
                        ?>
                    </h1>
                </div>
                <?php if($this->arrProductList){ ?>
                <div class="bar">
                    <div class="tabs">
                        <div class="item active" data-view="grid">
                            <div class="icon grid">

                            </div>
                        </div>
                        <div class="item" data-view="list">
                            <div class="icon list">

                            </div>
                        </div>
                    </div>

                    <div class="chonse">
                        <div class="sort">
                            <?php
                            $arrParams = array('controller' => 'brand', 'action' => 'index', 'brandSlug' => $brand, 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                            $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                            ?>
                            Sắp xếp
                            <select name="sort" id="sort">
                                <?php
                                $arrParams['sort'] = 'id_desc';
                                $linkSort = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'id_desc' ? 'selected' : null ?>>Sản phẩm mới</option>
                                <?php
                                $arrParams['sort'] = 'id_asc';
                                $linkSort = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'id_asc' ? 'selected' : null ?>>Sản phẩm cũ</option>
                                <?php
                                $arrParams['sort'] = 'price_desc';
                                $linkSort = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'price_desc' ? 'selected' : null ?>>Giá giảm dần</option>
                                <?php
                                $arrParams['sort'] = 'price_asc';
                                $linkSort = $this->serverUrl() . $this->Url('brand', $arrParams);
                                ?>
                                <option value="<?php echo $linkSort; ?>" <?php echo $this->params['sort'] == 'price_asc' ? 'selected' : null ?>>Giá tăng dần</option>
                            </select>
                        </div>
                        <?php
                        if ($this->countPage) {
                            $arrParams = array('controller' => 'brand', 'action' => 'index', 'brandSlug' => $brand, 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                            $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                            $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                            ?>
                            <div class="pagging">
                                Xem
                                <select name="page" class="view-page">
                                    <?php
                                    for ($i = 1; $i <= $this->countPage; $i++) {
                                        $arrParams['page'] = $i;
                                        $linkPage = $this->serverUrl() . $this->Url('brand', $arrParams);
                                        ?>
                                        <option value="<?php echo $linkPage; ?>" <?php echo $i == $this->params['page'] ? 'selected' : null ?>><?php echo $i; ?></option>
                                    <?php } ?>
                                </select> /  Trang
                            </div>
                        <?php } ?>
                    </div>
                </div>
                <?php } ?>
                <div class="sort-by">
                    <?php
                    $arrParams = array('controller' => 'brand', 'action' => 'index', 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug'], 'price' => $this->params['price']);
                    $this->params['s'] ? $arrParams['s'] = str_replace(' ', '+', $this->params['s']) : '';
                    $this->params['sort'] ? $arrParams['sort'] = str_replace(' ', '+', $this->params['sort']) : '';
                    if ($this->params['brand_name']) {
                        foreach ($this->params['brand_name'] as $val) {
                            ?>
                            <div class="item"><?php echo $val ?> <span class="remove remove-brand">X</span>
                                <?php
                                foreach ($this->arrBrandList as $value) {
                                    if ($value['cate_name'] == $val) {
                                        $arrParams['brandSlug'] = $brand . '--'; //ex : a--b--c--
                                        $arrParams['brandSlug'] = trim(str_replace($value['cate_slug'] . '--', NULL, $arrParams['brandSlug']), '--');

                                        $linkBrand = $this->serverUrl() . $this->Url('brand', $arrParams);
                                        ?>
                                        <input type="hidden" value="<?php echo count($this->params['brand_name']) == 1 ? $linkIndex : $linkBrand; ?>" />
                                        <?php
                                        break;
                                    }
                                }
                                ?>
                            </div>
                            <?php
                        }
                    }
                    $arrParams['brandSlug'] = $brand;
                    if ($this->params['categoryID']) {
                        $arrParams['categoryID'] = NULL;
                        $arrParams['categorySlug'] = NULL;
                        $linkCate = $this->serverUrl() . $this->Url('brand', $arrParams);
                        ?>
                        <div class="item">
                            <?php echo $this->params['cate_name']; ?> <span class="remove remove-category">X</span>
                            <input type="hidden" value="<?php echo $linkCate; ?>" />
                        </div>
                        <?php
                    }
                    if ($this->params['price']) {
                        $arrParams['price'] = NULL;
                        $arrParams['categoryID'] = $this->params['categoryID'];
                        $arrParams['categorySlug'] = $this->params['categorySlug'];
                        $linkPrice = $this->serverUrl() . $this->Url('brand', $arrParams);

                        $arrPrice = explode('--', $this->params['price']);
                        $price_start = number_format(abs((int) $arrPrice[0]), 0, '', '.');
                        $price_end = number_format(abs((int) $arrPrice[1]), 0, '', '.');
                        ?>
                        <div class="item">
                            <?php echo $price_start . ' - ' . $price_end; ?><span class="remove remove-price">X</span>
                            <input type="hidden" value="<?php echo $linkPrice; ?>" />
                        </div>
                    <?php } ?>
                    <?php
                    if ($this->params['price'] || $this->params['brand_name'] || $this->params['categoryID']) {
                        ?>
                        <div class="remove-all">
                            <?php
                            $linkRemoveAll = $this->serverUrl() . $this->Url('category', array('controller' => 'category', 'action' => 'index', 'categoryID' => $this->params['categoryID'], 'categorySlug' => $this->params['categorySlug']));
                            ?>
                            <a style="cursor: pointer" >Xóa tất cả</a>
                            <input type="hidden" value="<?php echo $this->params['categoryID'] ? $linkRemoveAll : $linkIndex; ?>" />
                        </div>
                    <?php } ?>
                    <div class="clear"></div>
                </div>
            </div>
            <div class="view-list grid">
                <?php
                if ($this->arrProductList) {
                    foreach ($this->arrProductList as $arrProductList) {
                        $prodLink = $this->serverUrl() . $this->Url('product', array('controller' => 'product', 'action' => 'detail', 'productslug' => $arrProductList["prod_slug"], 'productId' => $arrProductList['prod_id']));
                        ?>
                        <div class="item">
                            <div class="img">
                                <a href="<?php echo $prodLink ?>" rel="nofollow" title="<?php echo $arrProductList['prod_name']; ?>" ><img class="lazy" data-original="<?php echo json_decode($arrProductList['prod_image'], TRUE)['thumbImage']['224x224']; ?>" /></a>
                            </div>
                            <?php
                            if ($arrProductList['prod_call_price'] != 1):
                                if ($arrProductList['prod_is_promotion'] == 1):
                                    $percent = 100 - ($arrProductList['prod_promotion_price'] * 100 / $arrProductList['prod_price']);
                                    ?>
                                    <div class="icon">
                                        <!--<div class="gift"></div>-->
                                        <div class="discount">
                                            <?php
                                            echo number_format($percent, 0, ",", ".") . '%';
                                            ?>
                                        </div>
                                    </div>
                                    <?php
                                endif;
                            endif;
                            ?>
                            <div class="info">
                                <div class="title">
                                    <a href="<?php echo $prodLink ?>" title="<?php echo $arrProductList['prod_name']; ?>" ><?php echo $arrProductList['prod_name']; ?></a>
                                </div>
                                <div class="rate">
                                    <?php
                                    $rate = round($arrProductList['prod_rate'] / $arrProductList['prod_count_rate'], 0);
                                    $rate = (round(($rate / 2), 0) * 2);
//                                    $rate = $rate >= 5 ? $rate : 5;
                                    ?>
                                    <div class="star star-<?php echo $rate > 20 ? 20 : $rate; ?>"> <?php echo $rate ? '( ' . $arrProductList['prod_count_rate'] . ' đánh giá )' : '( ' . $arrProductList['prod_count_rate'] . ' đánh giá )'; ?></div> <!-- 5,10,15,20,25,30,35,40,45,50 -->
                                </div>
                                <div class="price">
                                    <div class="current">
                                        <?php
                                        if ($arrProductList['prod_call_price'])
                                            echo 'Liên hệ để biết giá';
                                        else if ($arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_promotion_price'], 0, '', '.') . ' VNĐ';
                                        else if (!$arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_price'], 0, '', '.') . ' VNĐ';
                                        ?>
                                    </div>
                                    <div class="promot">
                                        <?php
                                        if ($arrProductList['prod_call_price'])
                                            echo '';
                                        else if ($arrProductList['prod_is_promotion'] && !$arrProductList['prod_call_price'])
                                            echo number_format($arrProductList['prod_price'], 0, '', '.') . ' VNĐ';
                                        ?>
                                    </div>
                                </div>
                                <div class="desc">
                                    <?php echo $arrProductList['prod_description']; ?>
                                </div>
                                <div class="read-more"><a href="<?php echo $prodLink ?>">Xem chi tiết</a></div>
                            </div>
                        </div>
                        <?php
                    }
                }else {
                    ?>
                    <p>Không tìm thấy sản phẩm ... </p>
                <?php } ?>
                <div style="clear: both"></div>
            </div>
            <div class="paging">
                <?php echo $this->paging; ?>
            </div>
            <?php
            $description = $this->BrandDetailList[0]["cate_description"];
            //p($description);die;
            echo (trim($description) != "") ? '<div class="cate-content">' . $description . ' </div>' : '';
            ?>
        </div>
    </div>
    <div style="clear: both;"></div>
</div><!-- End block-content -->
<script>
    Brand.index();
</script>