<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h1>ĐĂNG NHẬP</h1>
                <h4>Đăng nhập vào chototquynhon.com</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="formSubmit">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <div class="user-form">
                    <div class="user-form-set">
                        <h4>LOGIN</h4>
                        <form method="post" class="form-group">
                            <div class="form-input">
                                <span class="fa fa-user form-control-feedback"></span>
                                <input class="form-control" type="text" name="user_name" placeholder="Tài khoản hoặc Email">
                            </div>
                            <div class="form-input">
                                <span class="fa fa-unlock-alt form-control-feedback"></span>
                                <input class="form-control" type="password" name="user_password" placeholder="Mật khẩu">
                            </div>
                            <div class="form-input">
                                <input type="checkbox" name="user_remember">
                                <label>Ghi nhớ cho lần sau</label>
                            </div>
                            <div class="form-input">
                                <input type="submit" value="ĐĂNG NHẬP">
                            </div>
                            <div class="form-input">
                                <p><a href="#">Quên mật khẩu ?</a></p>
                            </div>
                        </form>
                        <div class="social-login">
                            <h4>LOGIN VIA SOCIAL ACCOUNT</h4>
                            <div class="social-accounts">
                                <a href="#">
                                    <i class="fa fa-facebook"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </div>
                        </div>
                        <p>Bạn chưa có tài khoản ? <a href="#" class="col">Đăng ký ngay</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>