<?php
    use My\General;
    $general = new General();
    $gender = General::getGender();
?>
<!--main sub page heading-->
<section id="page-head">
    <div class="container">
        <div class="row col-md-12">
            <div class="page-heading">
                <h2>TÀI KHOẢN</h2>
                <h4>Đăng ký tài khoản</h4>
            </div>
        </div>
    </div>
</section><!--end main page heading-->
<section id="formSubmit">
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
                <div class="user-form">
                    <div class="user-form-set">
                        <h4>ĐĂNG KÝ TÀI KHOẢN</h4>
                        <form method="post" class="form-group">
                            <div class="form-input">
                                <span class="fa fa-user form-control-feedback"></span>
                                <input class="form-control" type="text" name="user_name" placeholder="Tài khoản" required data-validation-required-message="Bạn chưa nhập tài khoản" aria-invalid="false" value="<?php echo $params['user_name'];?>">
                            </div>
                            <div class="form-input">
                                <span class="fa fa-unlock-alt form-control-feedback"></span>
                                <input class="form-control" type="password" name="user_password" placeholder="Mật khẩu" required>
                            </div>
                            <div class="form-input">
                                <span class="fa fa-unlock-alt form-control-feedback"></span>
                                <input class="form-control" type="password" name="re_user_password" placeholder="Nhập lại Mật khẩu" required>
                            </div>
                            <div class="form-input">
                                <span class="fa fa-credit-card form-control-feedback"></span>
                                <input class="form-control" type="text" name="user_fullname" placeholder="Họ và tên" value="<?php echo $params['user_fullname'];?>">
                            </div>
                            <div class="form-input">
                                <span class="fa fa-at form-control-feedback"></span>
                                <input class="form-control" type="email" name="user_email" placeholder="Email" value="<?php echo $params['user_email'];?>">
                            </div>
                            <div class="form-input">
                                <span class="fa fa-phone form-control-feedback"></span>
                                <input class="form-control" type="date" name="user_phone" placeholder="Số điện thoại" value="<?php echo $params['user_phone'];?>">
                            </div>
							
							<div class="form-input">
                                <span class="fa fa-phone form-control-feedback"></span>
                                <input class="form-control" type="text" name="user_phone" placeholder="Số điện thoại" value="<?php echo $params['user_phone'];?>">
                            </div>
							
                            <div class="form-input">
                                <select class="form-control" name="user_gender">
                                    <?php foreach ($gender as $keygender => $valgender) : ?>
                                    <option value="<?php echo $keygender ?>">  <?php echo $valgender; ?></option>
                                    <?php endforeach; ?>
                                </select>
                            </div>
                            <div class="form-input">
                                <span><image class=" form-control img captcha"  src=""/></span>
                                <span class="fa fa-refresh fa-2x refresh"></span>
                                <input class="form-control" type="text" name="captcha" placeholder="Nhập mã xác nhận">
                            </div>
                            
                            <div class="form-input">
                                <input type="submit" value="ĐĂNG KÝ">
                            </div>
                        </form>
                        <div class="social-login">
                            <h4>LOGIN VIA SOCIAL ACCOUNT</h4>
                            <div class="social-accounts">
                                <a href="#">
                                    <i class="fa fa-facebook"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-twitter"></i>
                                </a>
                                <a href="#">
                                    <i class="fa fa-google-plus"></i>
                                </a>
                            </div>
                        </div>
                        <p>Login with Social</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    Auth.index();
</script>