<h3>Chúng tôi nhận được yêu cầu lấy lại mật khẩu từ bạn!</h3><br/>
Nếu đúng là yêu cầu của bạn! Xin vui lòng click vào link bên dưới để tiến hành reset mật khẩu:<br/>
<a href="<?php echo $this->serverUrl() . $this->Url('comfirm-forgot-password', array('randomKey' => $this->random_key)); ?>">Kích vào đây </a><br/><br/>
Nếu không phải là yêu cầu của bạn! Xin vui lòng bỏ qua!<br/><br/>
<h2><b>Chototquynhon.com - Mạng mua bán - rao vặt Quy Nhơn - Bình Định </b></h2>