<?php
$arrRole = $this->arrRole;
?>
<div id="content">
    <section class="wrapper site-min-height">
        <?php if ($this->errors): ?>
            <div class="alert alert-block alert-danger fade in">
                <button class="close close-sm" type="button" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <h4><i class="fa fa-times-sign"></i> Lỗi!</h4>
                <?php foreach ($this->errors as $error): ?>
                    <p> - <?php echo $error; ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>

        <?php
        $successMessage = array_merge($this->flashMessenger()->setNamespace('success-add-user')->getMessages(), $this->flashMessenger()->setNamespace('success-add-user')->getMessages());
        if ($successMessage):
            ?>
            <div class="alert alert-success alert-block fade in">
                <button class="close close-sm" type="button" data-dismiss="alert">
                    <i class="fa fa-times"></i>
                </button>
                <h4><i class="fa fa-ok-sign"></i> Hoàn tất!</h4>
                <p>- <?php echo current($successMessage); ?></p>
            </div>
        <?php endif; ?>
        <section class="panel">
            <header class="panel-heading">Đk</header>
            <div class="panel-body">

                <form id="frm" class="form-horizontal tasi-form" role="form" method="POST">
                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="name">Tên tk <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="name" name="name" class="form-control" type="text" placeholder="Vui lòng nhập tên tài khoản" value="<?php echo $this->params['name'] ? $this->params['name'] : ''; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="fullName">Họ và Tên <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="fullName" name="fullName" class="form-control" type="text" placeholder="Vui lòng nhập Họ và Tên" value="<?php echo $this->params['fullName'] ? $this->params['fullName'] : ''; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="email">Email <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="email" name="email" class="form-control" type="text" placeholder="Vui lòng nhập email" value="<?php echo $this->params['email'] ? $this->params['email'] : ''; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="fullName">Giới tính <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <select name="gender" id="gender" class="form-control">
                                <option value="1" <?php echo $this->params['gender'] == 1 ? "selected" : ''; ?>>Nam</option>
                                <option value="2" <?php echo $this->params['gender'] == 2 ? "selected" : ''; ?>>Nữ</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="birthdate">Ngày sinh</label>
                        <div class="col-lg-10">
                            <input id="birthdate" name="birthdate" class="form-control" type="text" placeholder="Vui lòng nhập ngày sinh" value="<?php echo $this->params['birthdate'] ? $this->params['birthdate'] : ''; ?>">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="phoneNumber">Số điện thoại <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="phoneNumber" name="phoneNumber" class="form-control" type="text" placeholder="Vui lòng nhập số điện thoại" value="<?php echo $this->params['phoneNumber'] ? $this->params['phoneNumber'] : ''; ?>" >
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="password">Mật khẩu <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="password" name="password" class="form-control" type="password" placeholder="Vui lòng nhập mật khẩu">
                        </div>
                    </div>

                    <div class="form-group">
                        <label class="col-lg-2 col-sm-2 control-label" for="retypePassword">Nhập lại mật khẩu <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="rePassword" name="rePassword" class="form-control" type="password" placeholder="Vui lòng nhập lại mật khẩu">
                        </div>
                    </div>

                    <div class="form-group">
                        <label  class="col-lg-2 control-label">Số nhà, tên đường,phường/xã <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <input id="address" name="address" class="form-control" type="text" placeholder="Lưu ý: Chỉ nhập số nhà - tên đường - Xã/ Phường" value="<?php echo $this->params['address'] ? $this->params['address'] : ''; ?>">
                            <label class="error" for="address" style="display: none;"></label>
                            <input type="hidden" name="fullAddress" id="fullAddress" value="<?php echo $this->arrUser['full_address']; ?>"/>
                        </div>
                    </div>

                    <div class="form-group">
                        <label  class="col-lg-2 control-label">Tỉnh / Thành <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <select name="city" id="city" class="form-control" >
                                <option value="">Vui lòng chọn Tỉnh / Thành</option>
                                <?php foreach ($this->arrCityList as $arrCity): ?>
                                    <option value="<?php echo $arrCity['city_id']; ?>" <?php echo $this->params['city'] == $arrCity['city_id'] ? "selected" : ''; ?>><?php echo $arrCity['city_name']; ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <label  class="col-lg-2 control-label">Quận / Huyện <span style="color:red">*</span></label>
                        <div class="col-lg-10">
                            <select name="district" id="district" class="form-control">
                                <option value="">Vui lòng chọn Quận / Huyện</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <img id="captcha" />
                        <input type="text" name="captcha" />
                    </div>

                    <div class="form-group">
                        <div class="col-lg-offset-2 col-lg-10">
                            <button type="submit" class="btn btn-success"><i class="icon-save"></i> Hoàn tất</button>
                        </div>
                    </div>

                </form>
            </div>

        </section>
    </section>
</div>
<script type="text/javascript">
    $.ajax({
        type: "POST",
        url: baseurl + '/frontend/captcha/index',
        success: function (result) {
            $('#captcha').attr('src', result);
        }
    });

    $('#city').change( function () {
        var city = $(this).find(':selected').val();
        $.ajax({
            type: "POST",
            url: baseurl + '/frontend/auth/changecity',
            cache: false,
            dataType: 'json',
            data: {
                city: city,
            },
            success: function (result) {
                var html = '';
                if (result.success === 1) {
                    for (var i = 0; i < result.data.length; i++) {
                        var item = result.data[i];
                        html += '<option value="' + item.dist_id + '">' + item.dist_name + '</option>';
                    }
                } else if (result.error === 1) {
                    html += '<option value="">Vui lòng chọn Quận / Huyện</option>';
                }
                $('#district').html(html);
            }
        });
    });
</script>
